# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\gui\ycircuit_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1089, 790)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Resources/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolButton_symbolPreviewFolder = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_symbolPreviewFolder.sizePolicy().hasHeightForWidth())
        self.toolButton_symbolPreviewFolder.setSizePolicy(sizePolicy)
        self.toolButton_symbolPreviewFolder.setMinimumSize(QtCore.QSize(0, 24))
        self.toolButton_symbolPreviewFolder.setMaximumSize(QtCore.QSize(110, 16777215))
        self.toolButton_symbolPreviewFolder.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton_symbolPreviewFolder.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolButton_symbolPreviewFolder.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton_symbolPreviewFolder.setObjectName("toolButton_symbolPreviewFolder")
        self.verticalLayout.addWidget(self.toolButton_symbolPreviewFolder)
        self.listView_symbolPreview = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_symbolPreview.sizePolicy().hasHeightForWidth())
        self.listView_symbolPreview.setSizePolicy(sizePolicy)
        self.listView_symbolPreview.setMinimumSize(QtCore.QSize(0, 0))
        self.listView_symbolPreview.setMaximumSize(QtCore.QSize(110, 16777215))
        self.listView_symbolPreview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView_symbolPreview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView_symbolPreview.setAutoScroll(True)
        self.listView_symbolPreview.setFlow(QtWidgets.QListView.TopToBottom)
        self.listView_symbolPreview.setProperty("isWrapping", False)
        self.listView_symbolPreview.setViewMode(QtWidgets.QListView.IconMode)
        self.listView_symbolPreview.setUniformItemSizes(True)
        self.listView_symbolPreview.setWordWrap(False)
        self.listView_symbolPreview.setObjectName("listView_symbolPreview")
        self.verticalLayout.addWidget(self.listView_symbolPreview)
        self.lineEdit_symbolPreviewFilter = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_symbolPreviewFilter.sizePolicy().hasHeightForWidth())
        self.lineEdit_symbolPreviewFilter.setSizePolicy(sizePolicy)
        self.lineEdit_symbolPreviewFilter.setMaximumSize(QtCore.QSize(110, 16777215))
        self.lineEdit_symbolPreviewFilter.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_symbolPreviewFilter.setClearButtonEnabled(False)
        self.lineEdit_symbolPreviewFilter.setObjectName("lineEdit_symbolPreviewFilter")
        self.verticalLayout.addWidget(self.lineEdit_symbolPreviewFilter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.drawingArea = DrawingArea(self.centralwidget)
        self.drawingArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.drawingArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.drawingArea.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.drawingArea.setDragMode(QtWidgets.QGraphicsView.RubberBandDrag)
        self.drawingArea.setCacheMode(QtWidgets.QGraphicsView.CacheBackground)
        self.drawingArea.setTransformationAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.drawingArea.setResizeAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.drawingArea.setViewportUpdateMode(QtWidgets.QGraphicsView.MinimalViewportUpdate)
        self.drawingArea.setRubberBandSelectionMode(QtCore.Qt.ContainsItemShape)
        self.drawingArea.setObjectName("drawingArea")
        self.horizontalLayout.addWidget(self.drawingArea)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listView_recentSymbols = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_recentSymbols.sizePolicy().hasHeightForWidth())
        self.listView_recentSymbols.setSizePolicy(sizePolicy)
        self.listView_recentSymbols.setMinimumSize(QtCore.QSize(0, 0))
        self.listView_recentSymbols.setMaximumSize(QtCore.QSize(110, 16777215))
        self.listView_recentSymbols.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView_recentSymbols.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listView_recentSymbols.setAutoScroll(True)
        self.listView_recentSymbols.setFlow(QtWidgets.QListView.TopToBottom)
        self.listView_recentSymbols.setProperty("isWrapping", False)
        self.listView_recentSymbols.setViewMode(QtWidgets.QListView.IconMode)
        self.listView_recentSymbols.setUniformItemSizes(True)
        self.listView_recentSymbols.setWordWrap(False)
        self.listView_recentSymbols.setObjectName("listView_recentSymbols")
        self.verticalLayout_3.addWidget(self.listView_recentSymbols)
        self.drawingAreaPreview = DrawingAreaPreview(self.centralwidget)
        self.drawingAreaPreview.setMaximumSize(QtCore.QSize(110, 110))
        self.drawingAreaPreview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.drawingAreaPreview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.drawingAreaPreview.setInteractive(False)
        self.drawingAreaPreview.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.drawingAreaPreview.setCacheMode(QtWidgets.QGraphicsView.CacheBackground)
        self.drawingAreaPreview.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.drawingAreaPreview.setObjectName("drawingAreaPreview")
        self.verticalLayout_3.addWidget(self.drawingAreaPreview)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setToolTipsVisible(True)
        self.menu_File.setObjectName("menu_File")
        self.menu_Edit = QtWidgets.QMenu(self.menubar)
        self.menu_Edit.setToolTipsVisible(True)
        self.menu_Edit.setObjectName("menu_Edit")
        self.menu_setPenWidth = QtWidgets.QMenu(self.menu_Edit)
        self.menu_setPenWidth.setToolTipsVisible(True)
        self.menu_setPenWidth.setObjectName("menu_setPenWidth")
        self.menu_setPenColour = QtWidgets.QMenu(self.menu_Edit)
        self.menu_setPenColour.setToolTipsVisible(True)
        self.menu_setPenColour.setObjectName("menu_setPenColour")
        self.menu_setPenStyle = QtWidgets.QMenu(self.menu_Edit)
        self.menu_setPenStyle.setToolTipsVisible(True)
        self.menu_setPenStyle.setObjectName("menu_setPenStyle")
        self.menu_setFillColour = QtWidgets.QMenu(self.menu_Edit)
        self.menu_setFillColour.setToolTipsVisible(True)
        self.menu_setFillColour.setObjectName("menu_setFillColour")
        self.menu_setFillStyle = QtWidgets.QMenu(self.menu_Edit)
        self.menu_setFillStyle.setToolTipsVisible(True)
        self.menu_setFillStyle.setObjectName("menu_setFillStyle")
        self.menuHeight = QtWidgets.QMenu(self.menu_Edit)
        self.menuHeight.setToolTipsVisible(True)
        self.menuHeight.setObjectName("menuHeight")
        self.menuGroup = QtWidgets.QMenu(self.menu_Edit)
        self.menuGroup.setToolTipsVisible(True)
        self.menuGroup.setObjectName("menuGroup")
        self.menu_setPenJoinStyle = QtWidgets.QMenu(self.menu_Edit)
        self.menu_setPenJoinStyle.setToolTipsVisible(True)
        self.menu_setPenJoinStyle.setObjectName("menu_setPenJoinStyle")
        self.men_setPenCapStyle = QtWidgets.QMenu(self.menu_Edit)
        self.men_setPenCapStyle.setToolTipsVisible(True)
        self.men_setPenCapStyle.setObjectName("men_setPenCapStyle")
        self.menu_AddSymbol = QtWidgets.QMenu(self.menubar)
        self.menu_AddSymbol.setToolTipsVisible(True)
        self.menu_AddSymbol.setObjectName("menu_AddSymbol")
        self.menu_Transistor = QtWidgets.QMenu(self.menu_AddSymbol)
        self.menu_Transistor.setToolTipsVisible(True)
        self.menu_Transistor.setObjectName("menu_Transistor")
        self.menu_N_type_MOSFET = QtWidgets.QMenu(self.menu_Transistor)
        self.menu_N_type_MOSFET.setToolTipsVisible(True)
        self.menu_N_type_MOSFET.setObjectName("menu_N_type_MOSFET")
        self.menu_P_type_MOSFET = QtWidgets.QMenu(self.menu_Transistor)
        self.menu_P_type_MOSFET.setToolTipsVisible(True)
        self.menu_P_type_MOSFET.setObjectName("menu_P_type_MOSFET")
        self.menuSources = QtWidgets.QMenu(self.menu_AddSymbol)
        self.menuSources.setToolTipsVisible(True)
        self.menuSources.setObjectName("menuSources")
        self.menu_DC = QtWidgets.QMenu(self.menuSources)
        self.menu_DC.setToolTipsVisible(True)
        self.menu_DC.setObjectName("menu_DC")
        self.menu_Controlled = QtWidgets.QMenu(self.menuSources)
        self.menu_Controlled.setToolTipsVisible(True)
        self.menu_Controlled.setObjectName("menu_Controlled")
        self.menu_quickAddSymbol = QtWidgets.QMenu(self.menu_AddSymbol)
        self.menu_quickAddSymbol.setToolTipsVisible(True)
        self.menu_quickAddSymbol.setObjectName("menu_quickAddSymbol")
        self.menu_View = QtWidgets.QMenu(self.menubar)
        self.menu_View.setToolTipsVisible(True)
        self.menu_View.setObjectName("menu_View")
        self.menuMajor_grid_point_spacing = QtWidgets.QMenu(self.menu_View)
        self.menuMajor_grid_point_spacing.setToolTipsVisible(True)
        self.menuMajor_grid_point_spacing.setObjectName("menuMajor_grid_point_spacing")
        self.menuMinor_grid_point_spacing = QtWidgets.QMenu(self.menu_View)
        self.menuMinor_grid_point_spacing.setToolTipsVisible(True)
        self.menuMinor_grid_point_spacing.setObjectName("menuMinor_grid_point_spacing")
        self.menuSnap_to_grid_spacing = QtWidgets.QMenu(self.menu_View)
        self.menuSnap_to_grid_spacing.setToolTipsVisible(True)
        self.menuSnap_to_grid_spacing.setObjectName("menuSnap_to_grid_spacing")
        self.menuSh_ape = QtWidgets.QMenu(self.menubar)
        self.menuSh_ape.setToolTipsVisible(True)
        self.menuSh_ape.setObjectName("menuSh_ape")
        self.menu_Arc = QtWidgets.QMenu(self.menuSh_ape)
        self.menu_Arc.setToolTipsVisible(True)
        self.menu_Arc.setObjectName("menu_Arc")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setToolTipsVisible(True)
        self.menu_help.setObjectName("menu_help")
        self.menu_tutorials = QtWidgets.QMenu(self.menu_help)
        self.menu_tutorials.setToolTipsVisible(True)
        self.menu_tutorials.setObjectName("menu_tutorials")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_exportFile = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/document-export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exportFile.setIcon(icon1)
        self.action_exportFile.setIconVisibleInMenu(False)
        self.action_exportFile.setObjectName("action_exportFile")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_move = QtWidgets.QAction(MainWindow)
        self.action_move.setCheckable(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/view-fullscreen.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_move.setIcon(icon2)
        self.action_move.setIconVisibleInMenu(False)
        self.action_move.setObjectName("action_move")
        self.action_copy = QtWidgets.QAction(MainWindow)
        self.action_copy.setCheckable(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/edit-copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_copy.setIcon(icon3)
        self.action_copy.setIconVisibleInMenu(False)
        self.action_copy.setObjectName("action_copy")
        self.action_addWire = QtWidgets.QAction(MainWindow)
        self.action_addWire.setObjectName("action_addWire")
        self.action_addResistor = QtWidgets.QAction(MainWindow)
        self.action_addResistor.setObjectName("action_addResistor")
        self.action_addDot = QtWidgets.QAction(MainWindow)
        self.action_addDot.setObjectName("action_addDot")
        self.action_setWidth2 = QtWidgets.QAction(MainWindow)
        self.action_setWidth2.setCheckable(True)
        self.action_setWidth2.setChecked(False)
        self.action_setWidth2.setObjectName("action_setWidth2")
        self.action_setWidth4 = QtWidgets.QAction(MainWindow)
        self.action_setWidth4.setCheckable(True)
        self.action_setWidth4.setChecked(False)
        self.action_setWidth4.setObjectName("action_setWidth4")
        self.action_setWidth6 = QtWidgets.QAction(MainWindow)
        self.action_setWidth6.setCheckable(True)
        self.action_setWidth6.setObjectName("action_setWidth6")
        self.action_setWidth8 = QtWidgets.QAction(MainWindow)
        self.action_setWidth8.setCheckable(True)
        self.action_setWidth8.setObjectName("action_setWidth8")
        self.action_setWidth10 = QtWidgets.QAction(MainWindow)
        self.action_setWidth10.setCheckable(True)
        self.action_setWidth10.setObjectName("action_setWidth10")
        self.action_rotate = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/object-rotate-right.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_rotate.setIcon(icon4)
        self.action_rotate.setIconVisibleInMenu(False)
        self.action_rotate.setObjectName("action_rotate")
        self.action_mirror = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/object-flip-horizontal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_mirror.setIcon(icon5)
        self.action_mirror.setIconVisibleInMenu(False)
        self.action_mirror.setObjectName("action_mirror")
        self.action_fitToView = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/view-restore.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_fitToView.setIcon(icon6)
        self.action_fitToView.setIconVisibleInMenu(False)
        self.action_fitToView.setObjectName("action_fitToView")
        self.action_showGrid = QtWidgets.QAction(MainWindow)
        self.action_showGrid.setCheckable(True)
        self.action_showGrid.setChecked(True)
        self.action_showGrid.setObjectName("action_showGrid")
        self.action_delete = QtWidgets.QAction(MainWindow)
        self.action_delete.setCheckable(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/list-remove.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_delete.setIcon(icon7)
        self.action_delete.setIconVisibleInMenu(False)
        self.action_delete.setObjectName("action_delete")
        self.action_setPenColourRed = QtWidgets.QAction(MainWindow)
        self.action_setPenColourRed.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/colours/colour_red.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenColourRed.setIcon(icon8)
        self.action_setPenColourRed.setObjectName("action_setPenColourRed")
        self.action_setPenColourBlue = QtWidgets.QAction(MainWindow)
        self.action_setPenColourBlue.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/colours/colour_blue.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenColourBlue.setIcon(icon9)
        self.action_setPenColourBlue.setObjectName("action_setPenColourBlue")
        self.action_setPenColourGreen = QtWidgets.QAction(MainWindow)
        self.action_setPenColourGreen.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/colours/colour_green.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenColourGreen.setIcon(icon10)
        self.action_setPenColourGreen.setObjectName("action_setPenColourGreen")
        self.action_setPenColourBlack = QtWidgets.QAction(MainWindow)
        self.action_setPenColourBlack.setCheckable(True)
        self.action_setPenColourBlack.setChecked(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/colours/colour_black.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenColourBlack.setIcon(icon11)
        self.action_setPenColourBlack.setObjectName("action_setPenColourBlack")
        self.action_setPenStyleSolid = QtWidgets.QAction(MainWindow)
        self.action_setPenStyleSolid.setCheckable(True)
        self.action_setPenStyleSolid.setChecked(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/penStyle/penStyle_solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenStyleSolid.setIcon(icon12)
        self.action_setPenStyleSolid.setObjectName("action_setPenStyleSolid")
        self.action_setPenStyleDash = QtWidgets.QAction(MainWindow)
        self.action_setPenStyleDash.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/penStyle/penStyle_dash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenStyleDash.setIcon(icon13)
        self.action_setPenStyleDash.setObjectName("action_setPenStyleDash")
        self.action_setPenStyleDot = QtWidgets.QAction(MainWindow)
        self.action_setPenStyleDot.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/penStyle/penStyle_dot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenStyleDot.setIcon(icon14)
        self.action_setPenStyleDot.setObjectName("action_setPenStyleDot")
        self.action_setPenStyleDashDot = QtWidgets.QAction(MainWindow)
        self.action_setPenStyleDashDot.setCheckable(True)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/penStyle/penStyle_dashDot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenStyleDashDot.setIcon(icon15)
        self.action_setPenStyleDashDot.setObjectName("action_setPenStyleDashDot")
        self.action_setPenStyleDashDotDot = QtWidgets.QAction(MainWindow)
        self.action_setPenStyleDashDotDot.setCheckable(True)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/penStyle/penStyle_dashDotDot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenStyleDashDotDot.setIcon(icon16)
        self.action_setPenStyleDashDotDot.setObjectName("action_setPenStyleDashDotDot")
        self.action_addCapacitor = QtWidgets.QAction(MainWindow)
        self.action_addCapacitor.setObjectName("action_addCapacitor")
        self.action_addGround = QtWidgets.QAction(MainWindow)
        self.action_addGround.setObjectName("action_addGround")
        self.action_setBrushColourBlack = QtWidgets.QAction(MainWindow)
        self.action_setBrushColourBlack.setCheckable(True)
        self.action_setBrushColourBlack.setChecked(False)
        self.action_setBrushColourBlack.setIcon(icon11)
        self.action_setBrushColourBlack.setObjectName("action_setBrushColourBlack")
        self.action_setBrushColourRed = QtWidgets.QAction(MainWindow)
        self.action_setBrushColourRed.setCheckable(True)
        self.action_setBrushColourRed.setIcon(icon8)
        self.action_setBrushColourRed.setObjectName("action_setBrushColourRed")
        self.action_setBrushColourBlue = QtWidgets.QAction(MainWindow)
        self.action_setBrushColourBlue.setCheckable(True)
        self.action_setBrushColourBlue.setIcon(icon9)
        self.action_setBrushColourBlue.setObjectName("action_setBrushColourBlue")
        self.action_setBrushColourGreen = QtWidgets.QAction(MainWindow)
        self.action_setBrushColourGreen.setCheckable(True)
        self.action_setBrushColourGreen.setIcon(icon10)
        self.action_setBrushColourGreen.setObjectName("action_setBrushColourGreen")
        self.action_setBrushStyleNone = QtWidgets.QAction(MainWindow)
        self.action_setBrushStyleNone.setCheckable(True)
        self.action_setBrushStyleNone.setChecked(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/brushStyle/brushStyle_noFill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setBrushStyleNone.setIcon(icon17)
        self.action_setBrushStyleNone.setObjectName("action_setBrushStyleNone")
        self.action_setBrushStyleSolid = QtWidgets.QAction(MainWindow)
        self.action_setBrushStyleSolid.setCheckable(True)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/brushStyle/brushStyle_solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setBrushStyleSolid.setIcon(icon18)
        self.action_setBrushStyleSolid.setObjectName("action_setBrushStyleSolid")
        self.action_addNPNBJT = QtWidgets.QAction(MainWindow)
        self.action_addNPNBJT.setObjectName("action_addNPNBJT")
        self.action_addPNPBJT = QtWidgets.QAction(MainWindow)
        self.action_addPNPBJT.setObjectName("action_addPNPBJT")
        self.action_addNMOSWithArrow = QtWidgets.QAction(MainWindow)
        self.action_addNMOSWithArrow.setObjectName("action_addNMOSWithArrow")
        self.action_addNMOSWithoutArrow = QtWidgets.QAction(MainWindow)
        self.action_addNMOSWithoutArrow.setObjectName("action_addNMOSWithoutArrow")
        self.action_addPMOSWithArrow = QtWidgets.QAction(MainWindow)
        self.action_addPMOSWithArrow.setObjectName("action_addPMOSWithArrow")
        self.action_addPMOSWithoutArrow = QtWidgets.QAction(MainWindow)
        self.action_addPMOSWithoutArrow.setObjectName("action_addPMOSWithoutArrow")
        self.action_saveSymbol = QtWidgets.QAction(MainWindow)
        self.action_saveSymbol.setObjectName("action_saveSymbol")
        self.action_loadSymbol = QtWidgets.QAction(MainWindow)
        self.action_loadSymbol.setObjectName("action_loadSymbol")
        self.action_saveSchematic = QtWidgets.QAction(MainWindow)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/icons/document-save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_saveSchematic.setIcon(icon19)
        self.action_saveSchematic.setIconVisibleInMenu(False)
        self.action_saveSchematic.setObjectName("action_saveSchematic")
        self.action_loadSchematic = QtWidgets.QAction(MainWindow)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/icons/document-open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_loadSchematic.setIcon(icon20)
        self.action_loadSchematic.setIconVisibleInMenu(False)
        self.action_loadSchematic.setObjectName("action_loadSchematic")
        self.action_addLine = QtWidgets.QAction(MainWindow)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/icons/insert-line.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_addLine.setIcon(icon21)
        self.action_addLine.setIconVisibleInMenu(False)
        self.action_addLine.setObjectName("action_addLine")
        self.action_addRectangle = QtWidgets.QAction(MainWindow)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/icons/insert-object.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_addRectangle.setIcon(icon22)
        self.action_addRectangle.setIconVisibleInMenu(False)
        self.action_addRectangle.setObjectName("action_addRectangle")
        self.action_addCircle = QtWidgets.QAction(MainWindow)
        self.action_addCircle.setObjectName("action_addCircle")
        self.action_addEllipse = QtWidgets.QAction(MainWindow)
        self.action_addEllipse.setObjectName("action_addEllipse")
        self.action_snapToGrid = QtWidgets.QAction(MainWindow)
        self.action_snapToGrid.setCheckable(True)
        self.action_snapToGrid.setChecked(True)
        self.action_snapToGrid.setObjectName("action_snapToGrid")
        self.action_addTextBox = QtWidgets.QAction(MainWindow)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/icons/insert-text.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_addTextBox.setIcon(icon23)
        self.action_addTextBox.setIconVisibleInMenu(False)
        self.action_addTextBox.setObjectName("action_addTextBox")
        self.action_setPenColourCyan = QtWidgets.QAction(MainWindow)
        self.action_setPenColourCyan.setCheckable(True)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/colours/colour_cyan.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenColourCyan.setIcon(icon24)
        self.action_setPenColourCyan.setObjectName("action_setPenColourCyan")
        self.action_setPenColourMagenta = QtWidgets.QAction(MainWindow)
        self.action_setPenColourMagenta.setCheckable(True)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/colours/colour_magenta.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenColourMagenta.setIcon(icon25)
        self.action_setPenColourMagenta.setObjectName("action_setPenColourMagenta")
        self.action_setPenColourYellow = QtWidgets.QAction(MainWindow)
        self.action_setPenColourYellow.setCheckable(True)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/colours/colour_yellow.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenColourYellow.setIcon(icon26)
        self.action_setPenColourYellow.setObjectName("action_setPenColourYellow")
        self.action_setBrushColourCyan = QtWidgets.QAction(MainWindow)
        self.action_setBrushColourCyan.setCheckable(True)
        self.action_setBrushColourCyan.setIcon(icon24)
        self.action_setBrushColourCyan.setObjectName("action_setBrushColourCyan")
        self.action_setBrushColourMagenta = QtWidgets.QAction(MainWindow)
        self.action_setBrushColourMagenta.setCheckable(True)
        self.action_setBrushColourMagenta.setIcon(icon25)
        self.action_setBrushColourMagenta.setObjectName("action_setBrushColourMagenta")
        self.action_setBrushColourYellow = QtWidgets.QAction(MainWindow)
        self.action_setBrushColourYellow.setCheckable(True)
        self.action_setBrushColourYellow.setIcon(icon26)
        self.action_setBrushColourYellow.setObjectName("action_setBrushColourYellow")
        self.action_addDCVoltageSource = QtWidgets.QAction(MainWindow)
        self.action_addDCVoltageSource.setObjectName("action_addDCVoltageSource")
        self.action_addDCCurrentSource = QtWidgets.QAction(MainWindow)
        self.action_addDCCurrentSource.setObjectName("action_addDCCurrentSource")
        self.action_addVCVS = QtWidgets.QAction(MainWindow)
        self.action_addVCVS.setObjectName("action_addVCVS")
        self.action_addVCCS = QtWidgets.QAction(MainWindow)
        self.action_addVCCS.setObjectName("action_addVCCS")
        self.action_addCCVS = QtWidgets.QAction(MainWindow)
        self.action_addCCVS.setObjectName("action_addCCVS")
        self.action_addCCCS = QtWidgets.QAction(MainWindow)
        self.action_addCCCS.setObjectName("action_addCCCS")
        self.action_addACSource = QtWidgets.QAction(MainWindow)
        self.action_addACSource.setObjectName("action_addACSource")
        self.action_addArc3Point = QtWidgets.QAction(MainWindow)
        self.action_addArc3Point.setObjectName("action_addArc3Point")
        self.action_addArc4Point = QtWidgets.QAction(MainWindow)
        self.action_addArc4Point.setObjectName("action_addArc4Point")
        self.action_undo = QtWidgets.QAction(MainWindow)
        self.action_undo.setEnabled(False)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(":/icons/edit-undo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_undo.setIcon(icon27)
        self.action_undo.setIconVisibleInMenu(False)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(MainWindow)
        self.action_redo.setEnabled(False)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(":/icons/edit-redo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_redo.setIcon(icon28)
        self.action_redo.setIconVisibleInMenu(False)
        self.action_redo.setObjectName("action_redo")
        self.action_saveSchematicAs = QtWidgets.QAction(MainWindow)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/icons/document-save-as.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_saveSchematicAs.setIcon(icon29)
        self.action_saveSchematicAs.setIconVisibleInMenu(False)
        self.action_saveSchematicAs.setObjectName("action_saveSchematicAs")
        self.action_saveSymbolAs = QtWidgets.QAction(MainWindow)
        self.action_saveSymbolAs.setObjectName("action_saveSymbolAs")
        self.action_modifySymbol = QtWidgets.QAction(MainWindow)
        self.action_modifySymbol.setObjectName("action_modifySymbol")
        self.action_editShape = QtWidgets.QAction(MainWindow)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/icons/gtk-edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_editShape.setIcon(icon30)
        self.action_editShape.setIconVisibleInMenu(False)
        self.action_editShape.setObjectName("action_editShape")
        self.action_newSchematic = QtWidgets.QAction(MainWindow)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/icons/document-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_newSchematic.setIcon(icon31)
        self.action_newSchematic.setIconVisibleInMenu(False)
        self.action_newSchematic.setObjectName("action_newSchematic")
        self.action_options = QtWidgets.QAction(MainWindow)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/icons/system-run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_options.setIcon(icon32)
        self.action_options.setIconVisibleInMenu(False)
        self.action_options.setObjectName("action_options")
        self.action_showMajorGridPoints = QtWidgets.QAction(MainWindow)
        self.action_showMajorGridPoints.setCheckable(True)
        self.action_showMajorGridPoints.setChecked(True)
        self.action_showMajorGridPoints.setObjectName("action_showMajorGridPoints")
        self.action_showMinorGridPoints = QtWidgets.QAction(MainWindow)
        self.action_showMinorGridPoints.setCheckable(True)
        self.action_showMinorGridPoints.setChecked(True)
        self.action_showMinorGridPoints.setObjectName("action_showMinorGridPoints")
        self.action_majorGridPointSpacing100 = QtWidgets.QAction(MainWindow)
        self.action_majorGridPointSpacing100.setCheckable(True)
        self.action_majorGridPointSpacing100.setChecked(True)
        self.action_majorGridPointSpacing100.setObjectName("action_majorGridPointSpacing100")
        self.action_majorGridPointSpacing200 = QtWidgets.QAction(MainWindow)
        self.action_majorGridPointSpacing200.setCheckable(True)
        self.action_majorGridPointSpacing200.setChecked(False)
        self.action_majorGridPointSpacing200.setObjectName("action_majorGridPointSpacing200")
        self.action_majorGridPointSpacing300 = QtWidgets.QAction(MainWindow)
        self.action_majorGridPointSpacing300.setCheckable(True)
        self.action_majorGridPointSpacing300.setObjectName("action_majorGridPointSpacing300")
        self.action_majorGridPointSpacing400 = QtWidgets.QAction(MainWindow)
        self.action_majorGridPointSpacing400.setCheckable(True)
        self.action_majorGridPointSpacing400.setObjectName("action_majorGridPointSpacing400")
        self.action_minorGridPointSpacing1 = QtWidgets.QAction(MainWindow)
        self.action_minorGridPointSpacing1.setCheckable(True)
        self.action_minorGridPointSpacing1.setObjectName("action_minorGridPointSpacing1")
        self.action_minorGridPointSpacing2 = QtWidgets.QAction(MainWindow)
        self.action_minorGridPointSpacing2.setCheckable(True)
        self.action_minorGridPointSpacing2.setObjectName("action_minorGridPointSpacing2")
        self.action_minorGridPointSpacing5 = QtWidgets.QAction(MainWindow)
        self.action_minorGridPointSpacing5.setCheckable(True)
        self.action_minorGridPointSpacing5.setObjectName("action_minorGridPointSpacing5")
        self.action_minorGridPointSpacing10 = QtWidgets.QAction(MainWindow)
        self.action_minorGridPointSpacing10.setCheckable(True)
        self.action_minorGridPointSpacing10.setObjectName("action_minorGridPointSpacing10")
        self.action_minorGridPointSpacing20 = QtWidgets.QAction(MainWindow)
        self.action_minorGridPointSpacing20.setCheckable(True)
        self.action_minorGridPointSpacing20.setChecked(True)
        self.action_minorGridPointSpacing20.setObjectName("action_minorGridPointSpacing20")
        self.action_minorGridPointSpacing30 = QtWidgets.QAction(MainWindow)
        self.action_minorGridPointSpacing30.setCheckable(True)
        self.action_minorGridPointSpacing30.setObjectName("action_minorGridPointSpacing30")
        self.action_minorGridPointSpacing40 = QtWidgets.QAction(MainWindow)
        self.action_minorGridPointSpacing40.setCheckable(True)
        self.action_minorGridPointSpacing40.setObjectName("action_minorGridPointSpacing40")
        self.action_snapToGridSpacing1 = QtWidgets.QAction(MainWindow)
        self.action_snapToGridSpacing1.setCheckable(True)
        self.action_snapToGridSpacing1.setObjectName("action_snapToGridSpacing1")
        self.action_snapToGridSpacing2 = QtWidgets.QAction(MainWindow)
        self.action_snapToGridSpacing2.setCheckable(True)
        self.action_snapToGridSpacing2.setObjectName("action_snapToGridSpacing2")
        self.action_snapToGridSpacing5 = QtWidgets.QAction(MainWindow)
        self.action_snapToGridSpacing5.setCheckable(True)
        self.action_snapToGridSpacing5.setObjectName("action_snapToGridSpacing5")
        self.action_snapToGridSpacing10 = QtWidgets.QAction(MainWindow)
        self.action_snapToGridSpacing10.setCheckable(True)
        self.action_snapToGridSpacing10.setObjectName("action_snapToGridSpacing10")
        self.action_snapToGridSpacing20 = QtWidgets.QAction(MainWindow)
        self.action_snapToGridSpacing20.setCheckable(True)
        self.action_snapToGridSpacing20.setObjectName("action_snapToGridSpacing20")
        self.action_snapToGridSpacing30 = QtWidgets.QAction(MainWindow)
        self.action_snapToGridSpacing30.setCheckable(True)
        self.action_snapToGridSpacing30.setObjectName("action_snapToGridSpacing30")
        self.action_snapToGridSpacing40 = QtWidgets.QAction(MainWindow)
        self.action_snapToGridSpacing40.setCheckable(True)
        self.action_snapToGridSpacing40.setObjectName("action_snapToGridSpacing40")
        self.action_setPenColourCustom = QtWidgets.QAction(MainWindow)
        self.action_setPenColourCustom.setObjectName("action_setPenColourCustom")
        self.action_setBrushColourCustom = QtWidgets.QAction(MainWindow)
        self.action_setBrushColourCustom.setObjectName("action_setBrushColourCustom")
        self.action_pickFont = QtWidgets.QAction(MainWindow)
        self.action_pickFont.setObjectName("action_pickFont")
        self.action_heightBringForward = QtWidgets.QAction(MainWindow)
        self.action_heightBringForward.setObjectName("action_heightBringForward")
        self.action_heightSendBack = QtWidgets.QAction(MainWindow)
        self.action_heightSendBack.setObjectName("action_heightSendBack")
        self.action_heightReset = QtWidgets.QAction(MainWindow)
        self.action_heightReset.setObjectName("action_heightReset")
        self.action_escape = QtWidgets.QAction(MainWindow)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/icons/edit-clear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_escape.setIcon(icon33)
        self.action_escape.setIconVisibleInMenu(False)
        self.action_escape.setObjectName("action_escape")
        self.action_group = QtWidgets.QAction(MainWindow)
        self.action_group.setObjectName("action_group")
        self.action_ungroup = QtWidgets.QAction(MainWindow)
        self.action_ungroup.setObjectName("action_ungroup")
        self.action_updateYCircuit = QtWidgets.QAction(MainWindow)
        self.action_updateYCircuit.setEnabled(False)
        self.action_updateYCircuit.setObjectName("action_updateYCircuit")
        self.action_tutorialInverterSchematic = QtWidgets.QAction(MainWindow)
        self.action_tutorialInverterSchematic.setObjectName("action_tutorialInverterSchematic")
        self.action_tutorialCustomSymbols = QtWidgets.QAction(MainWindow)
        self.action_tutorialCustomSymbols.setObjectName("action_tutorialCustomSymbols")
        self.action_setWidthCustom = QtWidgets.QAction(MainWindow)
        self.action_setWidthCustom.setObjectName("action_setWidthCustom")
        self.action_scale = QtWidgets.QAction(MainWindow)
        self.action_scale.setObjectName("action_scale")
        self.action_paste = QtWidgets.QAction(MainWindow)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/icons/edit-paste.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_paste.setIcon(icon34)
        self.action_paste.setIconVisibleInMenu(False)
        self.action_paste.setObjectName("action_paste")
        self.action_addImage = QtWidgets.QAction(MainWindow)
        self.action_addImage.setObjectName("action_addImage")
        self.action_importImage = QtWidgets.QAction(MainWindow)
        self.action_importImage.setObjectName("action_importImage")
        self.action_setPenJoinStyleRound = QtWidgets.QAction(MainWindow)
        self.action_setPenJoinStyleRound.setCheckable(True)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/penJoinStyle/penJoinStyle_round.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenJoinStyleRound.setIcon(icon35)
        self.action_setPenJoinStyleRound.setObjectName("action_setPenJoinStyleRound")
        self.action_setPenJoinStyleMiter = QtWidgets.QAction(MainWindow)
        self.action_setPenJoinStyleMiter.setCheckable(True)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/penJoinStyle/penJoinStyle_miter.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenJoinStyleMiter.setIcon(icon36)
        self.action_setPenJoinStyleMiter.setObjectName("action_setPenJoinStyleMiter")
        self.action_setPenJoinStyleBevel = QtWidgets.QAction(MainWindow)
        self.action_setPenJoinStyleBevel.setCheckable(True)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/penJoinStyle/penJoinStyle_bevel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenJoinStyleBevel.setIcon(icon37)
        self.action_setPenJoinStyleBevel.setObjectName("action_setPenJoinStyleBevel")
        self.action_setPenCapStyleSquare = QtWidgets.QAction(MainWindow)
        self.action_setPenCapStyleSquare.setCheckable(True)
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/penCapStyle/penCapStyle_square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenCapStyleSquare.setIcon(icon38)
        self.action_setPenCapStyleSquare.setObjectName("action_setPenCapStyleSquare")
        self.action_setPenCapStyleRound = QtWidgets.QAction(MainWindow)
        self.action_setPenCapStyleRound.setCheckable(True)
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/penCapStyle/penCapStyle_round.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenCapStyleRound.setIcon(icon39)
        self.action_setPenCapStyleRound.setObjectName("action_setPenCapStyleRound")
        self.action_setPenCapStyleFlat = QtWidgets.QAction(MainWindow)
        self.action_setPenCapStyleFlat.setCheckable(True)
        icon40 = QtGui.QIcon()
        icon40.addPixmap(QtGui.QPixmap(":/penCapStyle/penCapStyle_flat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_setPenCapStyleFlat.setIcon(icon40)
        self.action_setPenCapStyleFlat.setObjectName("action_setPenCapStyleFlat")
        self.action_quickAddSymbol1 = QtWidgets.QAction(MainWindow)
        self.action_quickAddSymbol1.setObjectName("action_quickAddSymbol1")
        self.action_quickAddSymbol2 = QtWidgets.QAction(MainWindow)
        self.action_quickAddSymbol2.setObjectName("action_quickAddSymbol2")
        self.action_quickAddSymbol3 = QtWidgets.QAction(MainWindow)
        self.action_quickAddSymbol3.setObjectName("action_quickAddSymbol3")
        self.action_quickAddSymbol4 = QtWidgets.QAction(MainWindow)
        self.action_quickAddSymbol4.setObjectName("action_quickAddSymbol4")
        self.action_quickAddSymbol5 = QtWidgets.QAction(MainWindow)
        self.action_quickAddSymbol5.setObjectName("action_quickAddSymbol5")
        self.action_showPins = QtWidgets.QAction(MainWindow)
        self.action_showPins.setCheckable(True)
        self.action_showPins.setChecked(True)
        self.action_showPins.setObjectName("action_showPins")
        self.action_addPin = QtWidgets.QAction(MainWindow)
        self.action_addPin.setObjectName("action_addPin")
        self.action_snapNetToPin = QtWidgets.QAction(MainWindow)
        self.action_snapNetToPin.setCheckable(True)
        self.action_snapNetToPin.setChecked(True)
        self.action_snapNetToPin.setObjectName("action_snapNetToPin")
        self.action_zoomIn = QtWidgets.QAction(MainWindow)
        icon41 = QtGui.QIcon()
        icon41.addPixmap(QtGui.QPixmap(":/icons/zoom-in.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_zoomIn.setIcon(icon41)
        self.action_zoomIn.setIconVisibleInMenu(False)
        self.action_zoomIn.setObjectName("action_zoomIn")
        self.action_zoomOut = QtWidgets.QAction(MainWindow)
        icon42 = QtGui.QIcon()
        icon42.addPixmap(QtGui.QPixmap(":/icons/zoom-out.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_zoomOut.setIcon(icon42)
        self.action_zoomOut.setIconVisibleInMenu(False)
        self.action_zoomOut.setObjectName("action_zoomOut")
        self.action_setScale = QtWidgets.QAction(MainWindow)
        self.action_setScale.setObjectName("action_setScale")
        self.menu_File.addAction(self.action_newSchematic)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_saveSchematic)
        self.menu_File.addAction(self.action_saveSchematicAs)
        self.menu_File.addAction(self.action_saveSymbol)
        self.menu_File.addAction(self.action_saveSymbolAs)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_loadSchematic)
        self.menu_File.addAction(self.action_loadSymbol)
        self.menu_File.addAction(self.action_modifySymbol)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_importImage)
        self.menu_File.addAction(self.action_exportFile)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_quit)
        self.menu_setPenWidth.addAction(self.action_setWidth2)
        self.menu_setPenWidth.addAction(self.action_setWidth4)
        self.menu_setPenWidth.addAction(self.action_setWidth6)
        self.menu_setPenWidth.addAction(self.action_setWidth8)
        self.menu_setPenWidth.addAction(self.action_setWidth10)
        self.menu_setPenWidth.addSeparator()
        self.menu_setPenWidth.addAction(self.action_setWidthCustom)
        self.menu_setPenColour.addAction(self.action_setPenColourBlack)
        self.menu_setPenColour.addAction(self.action_setPenColourRed)
        self.menu_setPenColour.addAction(self.action_setPenColourBlue)
        self.menu_setPenColour.addAction(self.action_setPenColourGreen)
        self.menu_setPenColour.addAction(self.action_setPenColourCyan)
        self.menu_setPenColour.addAction(self.action_setPenColourMagenta)
        self.menu_setPenColour.addAction(self.action_setPenColourYellow)
        self.menu_setPenColour.addSeparator()
        self.menu_setPenColour.addAction(self.action_setPenColourCustom)
        self.menu_setPenStyle.addAction(self.action_setPenStyleSolid)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDash)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDot)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDashDot)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDashDotDot)
        self.menu_setFillColour.addAction(self.action_setBrushColourBlack)
        self.menu_setFillColour.addAction(self.action_setBrushColourRed)
        self.menu_setFillColour.addAction(self.action_setBrushColourBlue)
        self.menu_setFillColour.addAction(self.action_setBrushColourGreen)
        self.menu_setFillColour.addAction(self.action_setBrushColourCyan)
        self.menu_setFillColour.addAction(self.action_setBrushColourMagenta)
        self.menu_setFillColour.addAction(self.action_setBrushColourYellow)
        self.menu_setFillColour.addSeparator()
        self.menu_setFillColour.addAction(self.action_setBrushColourCustom)
        self.menu_setFillStyle.addAction(self.action_setBrushStyleNone)
        self.menu_setFillStyle.addAction(self.action_setBrushStyleSolid)
        self.menuHeight.addAction(self.action_heightBringForward)
        self.menuHeight.addAction(self.action_heightSendBack)
        self.menuHeight.addSeparator()
        self.menuHeight.addAction(self.action_heightReset)
        self.menuGroup.addAction(self.action_group)
        self.menuGroup.addAction(self.action_ungroup)
        self.menu_setPenJoinStyle.addAction(self.action_setPenJoinStyleRound)
        self.menu_setPenJoinStyle.addAction(self.action_setPenJoinStyleMiter)
        self.menu_setPenJoinStyle.addAction(self.action_setPenJoinStyleBevel)
        self.men_setPenCapStyle.addAction(self.action_setPenCapStyleSquare)
        self.men_setPenCapStyle.addAction(self.action_setPenCapStyleRound)
        self.men_setPenCapStyle.addAction(self.action_setPenCapStyleFlat)
        self.menu_Edit.addAction(self.action_undo)
        self.menu_Edit.addAction(self.action_redo)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_delete)
        self.menu_Edit.addAction(self.action_move)
        self.menu_Edit.addAction(self.action_copy)
        self.menu_Edit.addAction(self.action_paste)
        self.menu_Edit.addAction(self.action_rotate)
        self.menu_Edit.addAction(self.action_mirror)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_pickFont)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.menuHeight.menuAction())
        self.menu_Edit.addAction(self.menuGroup.menuAction())
        self.menu_Edit.addAction(self.action_setScale)
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.menu_setPenWidth.menuAction())
        self.menu_Edit.addAction(self.menu_setPenColour.menuAction())
        self.menu_Edit.addAction(self.menu_setPenStyle.menuAction())
        self.menu_Edit.addAction(self.men_setPenCapStyle.menuAction())
        self.menu_Edit.addAction(self.menu_setPenJoinStyle.menuAction())
        self.menu_Edit.addAction(self.menu_setFillColour.menuAction())
        self.menu_Edit.addAction(self.menu_setFillStyle.menuAction())
        self.menu_Edit.addSeparator()
        self.menu_Edit.addAction(self.action_options)
        self.menu_N_type_MOSFET.addAction(self.action_addNMOSWithArrow)
        self.menu_N_type_MOSFET.addAction(self.action_addNMOSWithoutArrow)
        self.menu_P_type_MOSFET.addAction(self.action_addPMOSWithArrow)
        self.menu_P_type_MOSFET.addAction(self.action_addPMOSWithoutArrow)
        self.menu_Transistor.addAction(self.menu_N_type_MOSFET.menuAction())
        self.menu_Transistor.addAction(self.menu_P_type_MOSFET.menuAction())
        self.menu_Transistor.addAction(self.action_addNPNBJT)
        self.menu_Transistor.addAction(self.action_addPNPBJT)
        self.menu_DC.addAction(self.action_addDCVoltageSource)
        self.menu_DC.addAction(self.action_addDCCurrentSource)
        self.menu_Controlled.addAction(self.action_addVCVS)
        self.menu_Controlled.addAction(self.action_addVCCS)
        self.menu_Controlled.addAction(self.action_addCCVS)
        self.menu_Controlled.addAction(self.action_addCCCS)
        self.menuSources.addAction(self.menu_DC.menuAction())
        self.menuSources.addAction(self.action_addACSource)
        self.menuSources.addAction(self.menu_Controlled.menuAction())
        self.menu_quickAddSymbol.addAction(self.action_quickAddSymbol1)
        self.menu_quickAddSymbol.addAction(self.action_quickAddSymbol2)
        self.menu_quickAddSymbol.addAction(self.action_quickAddSymbol3)
        self.menu_quickAddSymbol.addAction(self.action_quickAddSymbol4)
        self.menu_quickAddSymbol.addAction(self.action_quickAddSymbol5)
        self.menu_AddSymbol.addAction(self.action_addPin)
        self.menu_AddSymbol.addSeparator()
        self.menu_AddSymbol.addAction(self.action_addWire)
        self.menu_AddSymbol.addAction(self.action_addResistor)
        self.menu_AddSymbol.addAction(self.action_addCapacitor)
        self.menu_AddSymbol.addAction(self.action_addGround)
        self.menu_AddSymbol.addAction(self.action_addDot)
        self.menu_AddSymbol.addAction(self.menu_Transistor.menuAction())
        self.menu_AddSymbol.addAction(self.menuSources.menuAction())
        self.menu_AddSymbol.addSeparator()
        self.menu_AddSymbol.addAction(self.menu_quickAddSymbol.menuAction())
        self.menuMajor_grid_point_spacing.addAction(self.action_majorGridPointSpacing100)
        self.menuMajor_grid_point_spacing.addAction(self.action_majorGridPointSpacing200)
        self.menuMajor_grid_point_spacing.addAction(self.action_majorGridPointSpacing300)
        self.menuMajor_grid_point_spacing.addAction(self.action_majorGridPointSpacing400)
        self.menuMinor_grid_point_spacing.addAction(self.action_minorGridPointSpacing1)
        self.menuMinor_grid_point_spacing.addAction(self.action_minorGridPointSpacing2)
        self.menuMinor_grid_point_spacing.addAction(self.action_minorGridPointSpacing5)
        self.menuMinor_grid_point_spacing.addAction(self.action_minorGridPointSpacing10)
        self.menuMinor_grid_point_spacing.addAction(self.action_minorGridPointSpacing20)
        self.menuMinor_grid_point_spacing.addAction(self.action_minorGridPointSpacing30)
        self.menuMinor_grid_point_spacing.addAction(self.action_minorGridPointSpacing40)
        self.menuSnap_to_grid_spacing.addAction(self.action_snapToGridSpacing1)
        self.menuSnap_to_grid_spacing.addAction(self.action_snapToGridSpacing2)
        self.menuSnap_to_grid_spacing.addAction(self.action_snapToGridSpacing5)
        self.menuSnap_to_grid_spacing.addAction(self.action_snapToGridSpacing10)
        self.menuSnap_to_grid_spacing.addAction(self.action_snapToGridSpacing20)
        self.menuSnap_to_grid_spacing.addAction(self.action_snapToGridSpacing30)
        self.menuSnap_to_grid_spacing.addAction(self.action_snapToGridSpacing40)
        self.menu_View.addAction(self.action_zoomIn)
        self.menu_View.addAction(self.action_zoomOut)
        self.menu_View.addAction(self.action_fitToView)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.action_showPins)
        self.menu_View.addAction(self.action_snapNetToPin)
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.action_showGrid)
        self.menu_View.addAction(self.action_snapToGrid)
        self.menu_View.addAction(self.menuSnap_to_grid_spacing.menuAction())
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.action_showMajorGridPoints)
        self.menu_View.addAction(self.menuMajor_grid_point_spacing.menuAction())
        self.menu_View.addSeparator()
        self.menu_View.addAction(self.action_showMinorGridPoints)
        self.menu_View.addAction(self.menuMinor_grid_point_spacing.menuAction())
        self.menu_Arc.addAction(self.action_addArc3Point)
        self.menu_Arc.addAction(self.action_addArc4Point)
        self.menuSh_ape.addAction(self.action_addLine)
        self.menuSh_ape.addAction(self.menu_Arc.menuAction())
        self.menuSh_ape.addAction(self.action_addRectangle)
        self.menuSh_ape.addAction(self.action_addCircle)
        self.menuSh_ape.addAction(self.action_addEllipse)
        self.menuSh_ape.addSeparator()
        self.menuSh_ape.addAction(self.action_addTextBox)
        self.menuSh_ape.addAction(self.action_addImage)
        self.menuSh_ape.addSeparator()
        self.menuSh_ape.addAction(self.action_editShape)
        self.menu_tutorials.addAction(self.action_tutorialInverterSchematic)
        self.menu_tutorials.addAction(self.action_tutorialCustomSymbols)
        self.menu_help.addAction(self.action_updateYCircuit)
        self.menu_help.addAction(self.menu_tutorials.menuAction())
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuSh_ape.menuAction())
        self.menubar.addAction(self.menu_AddSymbol.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())
        self.toolBar.addAction(self.action_newSchematic)
        self.toolBar.addAction(self.action_saveSchematic)
        self.toolBar.addAction(self.action_loadSchematic)
        self.toolBar.addAction(self.action_exportFile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_undo)
        self.toolBar.addAction(self.action_redo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_zoomIn)
        self.toolBar.addAction(self.action_fitToView)
        self.toolBar.addAction(self.action_zoomOut)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_delete)
        self.toolBar.addAction(self.action_move)
        self.toolBar.addAction(self.action_copy)
        self.toolBar.addAction(self.action_paste)
        self.toolBar.addAction(self.action_rotate)
        self.toolBar.addAction(self.action_mirror)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_addLine)
        self.toolBar.addAction(self.action_addRectangle)
        self.toolBar.addAction(self.action_addTextBox)
        self.toolBar.addAction(self.action_editShape)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_options)
        self.toolBar.addAction(self.action_escape)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "YCircuit"))
        self.toolButton_symbolPreviewFolder.setToolTip(_translate("MainWindow", "Pick the folder to show symbol previews for. The folders in the drop-down menu can be customized through Options."))
        self.toolButton_symbolPreviewFolder.setText(_translate("MainWindow", "Symbol folder"))
        self.lineEdit_symbolPreviewFilter.setPlaceholderText(_translate("MainWindow", "Filter (Ctrl+F)..."))
        self.menu_File.setTitle(_translate("MainWindow", "&File"))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit"))
        self.menu_setPenWidth.setToolTip(_translate("MainWindow", "Modify the width of the pen used for drawing items"))
        self.menu_setPenWidth.setTitle(_translate("MainWindow", "&Width"))
        self.menu_setPenColour.setToolTip(_translate("MainWindow", "Modify the colour of the pen used for drawing items"))
        self.menu_setPenColour.setTitle(_translate("MainWindow", "&Colour"))
        self.menu_setPenStyle.setToolTip(_translate("MainWindow", "Modify the style of the pen used for drawing items"))
        self.menu_setPenStyle.setTitle(_translate("MainWindow", "&Pen style"))
        self.menu_setFillColour.setToolTip(_translate("MainWindow", "Modify the colour of the brush used for filling items"))
        self.menu_setFillColour.setTitle(_translate("MainWindow", "Fill colour"))
        self.menu_setFillStyle.setToolTip(_translate("MainWindow", "Modify the style of the brush used for filling items"))
        self.menu_setFillStyle.setTitle(_translate("MainWindow", "Fill style"))
        self.menuHeight.setToolTip(_translate("MainWindow", "Modify the height of the selected item(s). Items with larger heights are placed in front of those with lower heights."))
        self.menuHeight.setTitle(_translate("MainWindow", "Height"))
        self.menuGroup.setToolTip(_translate("MainWindow", "Group selected items together"))
        self.menuGroup.setTitle(_translate("MainWindow", "Group"))
        self.menu_setPenJoinStyle.setToolTip(_translate("MainWindow", "Modify the pen join style used for drawing items"))
        self.menu_setPenJoinStyle.setTitle(_translate("MainWindow", "&Join style"))
        self.men_setPenCapStyle.setTitle(_translate("MainWindow", "Cap style"))
        self.menu_AddSymbol.setTitle(_translate("MainWindow", "&Symbol"))
        self.menu_Transistor.setToolTip(_translate("MainWindow", "Add from a variety of transistors"))
        self.menu_Transistor.setTitle(_translate("MainWindow", "&Transistor"))
        self.menu_N_type_MOSFET.setToolTip(_translate("MainWindow", "Add N-type MOSFETs"))
        self.menu_N_type_MOSFET.setTitle(_translate("MainWindow", "&N-type MOSFET"))
        self.menu_P_type_MOSFET.setToolTip(_translate("MainWindow", "Add P-type MOSFETs"))
        self.menu_P_type_MOSFET.setTitle(_translate("MainWindow", "&P-type MOSFET"))
        self.menuSources.setToolTip(_translate("MainWindow", "Add from a variety of sources"))
        self.menuSources.setTitle(_translate("MainWindow", "&Sources"))
        self.menu_DC.setToolTip(_translate("MainWindow", "Add from a variety of DC sources"))
        self.menu_DC.setTitle(_translate("MainWindow", "&DC"))
        self.menu_Controlled.setToolTip(_translate("MainWindow", "Add from a variety of controlled sources"))
        self.menu_Controlled.setTitle(_translate("MainWindow", "&Controlled"))
        self.menu_quickAddSymbol.setToolTip(_translate("MainWindow", "Create a list of quick access symbols"))
        self.menu_quickAddSymbol.setTitle(_translate("MainWindow", "Quick add"))
        self.menu_View.setTitle(_translate("MainWindow", "&View"))
        self.menuMajor_grid_point_spacing.setToolTip(_translate("MainWindow", "Modify the spacing of the major grid points"))
        self.menuMajor_grid_point_spacing.setTitle(_translate("MainWindow", "Major grid point spacing"))
        self.menuMinor_grid_point_spacing.setToolTip(_translate("MainWindow", "Modify the spacing of the minor grid points"))
        self.menuMinor_grid_point_spacing.setTitle(_translate("MainWindow", "Minor grid point spacing"))
        self.menuSnap_to_grid_spacing.setToolTip(_translate("MainWindow", "Modify the value of the grid used for snapping"))
        self.menuSnap_to_grid_spacing.setTitle(_translate("MainWindow", "Snap to grid spacing"))
        self.menuSh_ape.setTitle(_translate("MainWindow", "Sh&ape"))
        self.menu_Arc.setToolTip(_translate("MainWindow", "Draw a 3-point or 4-point arc"))
        self.menu_Arc.setTitle(_translate("MainWindow", "&Arc"))
        self.menu_help.setTitle(_translate("MainWindow", "&Help"))
        self.menu_tutorials.setTitle(_translate("MainWindow", "Tutorials"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_exportFile.setText(_translate("MainWindow", "Export file"))
        self.action_exportFile.setToolTip(_translate("MainWindow", "Exports current window to a variety of formats"))
        self.action_exportFile.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.action_quit.setText(_translate("MainWindow", "Quit"))
        self.action_quit.setToolTip(_translate("MainWindow", "Quits the program"))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.action_move.setText(_translate("MainWindow", "Move"))
        self.action_move.setToolTip(_translate("MainWindow", "Move selected item(s)"))
        self.action_move.setShortcut(_translate("MainWindow", "M"))
        self.action_copy.setText(_translate("MainWindow", "Copy"))
        self.action_copy.setToolTip(_translate("MainWindow", "Copy selected item(s)"))
        self.action_copy.setShortcut(_translate("MainWindow", "C"))
        self.action_addWire.setText(_translate("MainWindow", "Wire"))
        self.action_addWire.setToolTip(_translate("MainWindow", "Add a wire to connect components"))
        self.action_addWire.setShortcut(_translate("MainWindow", "W"))
        self.action_addResistor.setText(_translate("MainWindow", "&Resistor"))
        self.action_addResistor.setToolTip(_translate("MainWindow", "Add a resistor"))
        self.action_addDot.setText(_translate("MainWindow", "Connection &dot"))
        self.action_addDot.setToolTip(_translate("MainWindow", "Add a dot signifying connectivity"))
        self.action_setWidth2.setText(_translate("MainWindow", "2"))
        self.action_setWidth2.setToolTip(_translate("MainWindow", "Sets the width of currently selected item(s) to 2"))
        self.action_setWidth4.setText(_translate("MainWindow", "4"))
        self.action_setWidth4.setToolTip(_translate("MainWindow", "Sets the width of currently selected item(s) to 4"))
        self.action_setWidth6.setText(_translate("MainWindow", "6"))
        self.action_setWidth6.setToolTip(_translate("MainWindow", "Sets the width of currently selected item(s) to 6"))
        self.action_setWidth8.setText(_translate("MainWindow", "8"))
        self.action_setWidth8.setToolTip(_translate("MainWindow", "Sets the width of currently selected item(s) to 8"))
        self.action_setWidth10.setText(_translate("MainWindow", "10"))
        self.action_setWidth10.setToolTip(_translate("MainWindow", "Sets the width of currently selected item(s) to 10"))
        self.action_rotate.setText(_translate("MainWindow", "Rotate"))
        self.action_rotate.setToolTip(_translate("MainWindow", "Rotate selected item(s)"))
        self.action_rotate.setShortcut(_translate("MainWindow", "R"))
        self.action_mirror.setText(_translate("MainWindow", "Mirror"))
        self.action_mirror.setToolTip(_translate("MainWindow", "Mirror selected item(s)"))
        self.action_mirror.setShortcut(_translate("MainWindow", "Shift+R"))
        self.action_fitToView.setText(_translate("MainWindow", "Fit to view"))
        self.action_fitToView.setToolTip(_translate("MainWindow", "Set the view such that all items are visible"))
        self.action_fitToView.setShortcut(_translate("MainWindow", "F"))
        self.action_showGrid.setText(_translate("MainWindow", "Show grid"))
        self.action_showGrid.setToolTip(_translate("MainWindow", "Toggle grid visibility"))
        self.action_delete.setText(_translate("MainWindow", "Delete"))
        self.action_delete.setToolTip(_translate("MainWindow", "Delete selected item(s)"))
        self.action_delete.setShortcut(_translate("MainWindow", "D"))
        self.action_setPenColourRed.setText(_translate("MainWindow", "&Red"))
        self.action_setPenColourRed.setToolTip(_translate("MainWindow", "Set the colour of selected item(s) to red"))
        self.action_setPenColourBlue.setText(_translate("MainWindow", "&Blue"))
        self.action_setPenColourBlue.setToolTip(_translate("MainWindow", "Set the colour of selected item(s) to blue"))
        self.action_setPenColourGreen.setText(_translate("MainWindow", "&Green"))
        self.action_setPenColourGreen.setToolTip(_translate("MainWindow", "Set the colour of selected item(s) to green"))
        self.action_setPenColourBlack.setText(_translate("MainWindow", "Blac&k"))
        self.action_setPenColourBlack.setToolTip(_translate("MainWindow", "Set the colour of selected item(s) to black"))
        self.action_setPenStyleSolid.setText(_translate("MainWindow", "&Solid"))
        self.action_setPenStyleSolid.setToolTip(_translate("MainWindow", "Set pen style for selected item(s) to solid"))
        self.action_setPenStyleDash.setText(_translate("MainWindow", "&Dash"))
        self.action_setPenStyleDash.setToolTip(_translate("MainWindow", "Set pen style for selected item(s) to dash"))
        self.action_setPenStyleDot.setText(_translate("MainWindow", "Do&t"))
        self.action_setPenStyleDot.setToolTip(_translate("MainWindow", "Set pen style for selected item(s) to dot"))
        self.action_setPenStyleDashDot.setText(_translate("MainWindow", "D&ash-Dot"))
        self.action_setPenStyleDashDot.setToolTip(_translate("MainWindow", "Set pen style for selected item(s) to dash-dot"))
        self.action_setPenStyleDashDotDot.setText(_translate("MainWindow", "Dash-dot-dot"))
        self.action_setPenStyleDashDotDot.setToolTip(_translate("MainWindow", "Set pen style for selected item(s) to dash-dot-dot"))
        self.action_addCapacitor.setText(_translate("MainWindow", "&Capacitor"))
        self.action_addCapacitor.setToolTip(_translate("MainWindow", "Add a capacitor"))
        self.action_addGround.setText(_translate("MainWindow", "&Ground"))
        self.action_addGround.setToolTip(_translate("MainWindow", "Add a ground symbol"))
        self.action_setBrushColourBlack.setText(_translate("MainWindow", "Blac&k"))
        self.action_setBrushColourBlack.setToolTip(_translate("MainWindow", "Sets the fill colour to black"))
        self.action_setBrushColourRed.setText(_translate("MainWindow", "&Red"))
        self.action_setBrushColourRed.setToolTip(_translate("MainWindow", "Set the fill colour to red"))
        self.action_setBrushColourBlue.setText(_translate("MainWindow", "&Blue"))
        self.action_setBrushColourBlue.setToolTip(_translate("MainWindow", "Set the fill colour to blue"))
        self.action_setBrushColourGreen.setText(_translate("MainWindow", "&Green"))
        self.action_setBrushColourGreen.setToolTip(_translate("MainWindow", "Set the brush colour to green"))
        self.action_setBrushStyleNone.setText(_translate("MainWindow", "&No fill"))
        self.action_setBrushStyleNone.setToolTip(_translate("MainWindow", "Remove any fill"))
        self.action_setBrushStyleSolid.setText(_translate("MainWindow", "&Solid"))
        self.action_setBrushStyleSolid.setToolTip(_translate("MainWindow", "Fill with a solid colour"))
        self.action_addNPNBJT.setText(_translate("MainWindow", "NPN BJT"))
        self.action_addNPNBJT.setToolTip(_translate("MainWindow", "Add NPN BJT"))
        self.action_addPNPBJT.setText(_translate("MainWindow", "PNP BJT"))
        self.action_addPNPBJT.setToolTip(_translate("MainWindow", "Add PNP BJT"))
        self.action_addNMOSWithArrow.setText(_translate("MainWindow", "With &arrow"))
        self.action_addNMOSWithArrow.setToolTip(_translate("MainWindow", "Add N-type MOSFET with arrow"))
        self.action_addNMOSWithoutArrow.setText(_translate("MainWindow", "Without arrow"))
        self.action_addNMOSWithoutArrow.setToolTip(_translate("MainWindow", "Add N-type MOSFET without arrow"))
        self.action_addPMOSWithArrow.setText(_translate("MainWindow", "With &arrow"))
        self.action_addPMOSWithArrow.setToolTip(_translate("MainWindow", "Add P-type MOSFET with arrow"))
        self.action_addPMOSWithoutArrow.setText(_translate("MainWindow", "Without arrow"))
        self.action_addPMOSWithoutArrow.setToolTip(_translate("MainWindow", "Add P-type MOSFET without arrow"))
        self.action_saveSymbol.setText(_translate("MainWindow", "Save symbol"))
        self.action_saveSymbol.setToolTip(_translate("MainWindow", "Save current symbol"))
        self.action_saveSymbol.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_loadSymbol.setText(_translate("MainWindow", "Load symbol"))
        self.action_loadSymbol.setToolTip(_translate("MainWindow", "Load a symbol from disk"))
        self.action_loadSymbol.setShortcut(_translate("MainWindow", "Ctrl+Shift+L"))
        self.action_saveSchematic.setText(_translate("MainWindow", "Save schematic"))
        self.action_saveSchematic.setToolTip(_translate("MainWindow", "Save current schematic"))
        self.action_saveSchematic.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_loadSchematic.setText(_translate("MainWindow", "Load schematic"))
        self.action_loadSchematic.setToolTip(_translate("MainWindow", "Load a schematic from disk (will clear out any work that you\'ve done thus far in this window)"))
        self.action_loadSchematic.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.action_addLine.setText(_translate("MainWindow", "&Line"))
        self.action_addLine.setToolTip(_translate("MainWindow", "Draw a polyline"))
        self.action_addRectangle.setText(_translate("MainWindow", "&Rectangle"))
        self.action_addRectangle.setToolTip(_translate("MainWindow", "Draw a rectangle"))
        self.action_addCircle.setText(_translate("MainWindow", "&Circle"))
        self.action_addCircle.setToolTip(_translate("MainWindow", "Draw a circle"))
        self.action_addEllipse.setText(_translate("MainWindow", "&Ellipse"))
        self.action_addEllipse.setToolTip(_translate("MainWindow", "Draw an ellipse"))
        self.action_snapToGrid.setText(_translate("MainWindow", "Sn&ap to grid"))
        self.action_snapToGrid.setToolTip(_translate("MainWindow", "Toggle snapping to the grid"))
        self.action_addTextBox.setText(_translate("MainWindow", "&Text box"))
        self.action_addTextBox.setToolTip(_translate("MainWindow", "Create a text box"))
        self.action_setPenColourCyan.setText(_translate("MainWindow", "&Cyan"))
        self.action_setPenColourCyan.setToolTip(_translate("MainWindow", "Set the colour of selected item(s) to cyan"))
        self.action_setPenColourMagenta.setText(_translate("MainWindow", "&Magenta"))
        self.action_setPenColourMagenta.setToolTip(_translate("MainWindow", "Set the colour of selected item(s) to magenta"))
        self.action_setPenColourYellow.setText(_translate("MainWindow", "&Yellow"))
        self.action_setPenColourYellow.setToolTip(_translate("MainWindow", "Set the colour of selected item(s) to yellow"))
        self.action_setBrushColourCyan.setText(_translate("MainWindow", "&Cyan"))
        self.action_setBrushColourCyan.setToolTip(_translate("MainWindow", "Set the brush colour to cyan"))
        self.action_setBrushColourMagenta.setText(_translate("MainWindow", "&Magenta"))
        self.action_setBrushColourMagenta.setToolTip(_translate("MainWindow", "Set the brush colour to magenta"))
        self.action_setBrushColourYellow.setText(_translate("MainWindow", "&Yellow"))
        self.action_setBrushColourYellow.setToolTip(_translate("MainWindow", "Set the brush colour to yellow"))
        self.action_addDCVoltageSource.setText(_translate("MainWindow", "&Voltage"))
        self.action_addDCVoltageSource.setToolTip(_translate("MainWindow", "Add a DC voltage source"))
        self.action_addDCCurrentSource.setText(_translate("MainWindow", "&Current"))
        self.action_addDCCurrentSource.setToolTip(_translate("MainWindow", "Add a DC current source"))
        self.action_addVCVS.setText(_translate("MainWindow", "VCVS"))
        self.action_addVCVS.setToolTip(_translate("MainWindow", "Add a VCVS"))
        self.action_addVCCS.setText(_translate("MainWindow", "VCCS"))
        self.action_addVCCS.setToolTip(_translate("MainWindow", "Add a VCCS"))
        self.action_addCCVS.setText(_translate("MainWindow", "CCVS"))
        self.action_addCCVS.setToolTip(_translate("MainWindow", "Add a CCVS"))
        self.action_addCCCS.setText(_translate("MainWindow", "CCCS"))
        self.action_addCCCS.setToolTip(_translate("MainWindow", "Add a CCCS"))
        self.action_addACSource.setText(_translate("MainWindow", "&AC"))
        self.action_addACSource.setToolTip(_translate("MainWindow", "Add an AC source"))
        self.action_addArc3Point.setText(_translate("MainWindow", "&3-point"))
        self.action_addArc3Point.setToolTip(_translate("MainWindow", "Draw a 3-point Bezier curve"))
        self.action_addArc4Point.setText(_translate("MainWindow", "&4-point"))
        self.action_addArc4Point.setToolTip(_translate("MainWindow", "Draw a 4-point Bezier curve"))
        self.action_undo.setText(_translate("MainWindow", "Undo"))
        self.action_undo.setToolTip(_translate("MainWindow", "Undo the previous action"))
        self.action_undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_redo.setText(_translate("MainWindow", "Redo"))
        self.action_redo.setToolTip(_translate("MainWindow", "Redo the previously undid action"))
        self.action_redo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.action_saveSchematicAs.setText(_translate("MainWindow", "Save s&chematic as"))
        self.action_saveSchematicAs.setToolTip(_translate("MainWindow", "Save current schematic with a new file name"))
        self.action_saveSymbolAs.setText(_translate("MainWindow", "Save &symbol as"))
        self.action_saveSymbolAs.setToolTip(_translate("MainWindow", "Save current symbol with a new file name"))
        self.action_modifySymbol.setText(_translate("MainWindow", "&Modify symbol"))
        self.action_modifySymbol.setToolTip(_translate("MainWindow", "Modify an existing symbol (will clear out any work that you\'ve done thus far in this window)"))
        self.action_editShape.setText(_translate("MainWindow", "Edit shape"))
        self.action_editShape.setToolTip(_translate("MainWindow", "Edit selected shape"))
        self.action_editShape.setShortcut(_translate("MainWindow", "E"))
        self.action_newSchematic.setText(_translate("MainWindow", "New Schematic"))
        self.action_newSchematic.setToolTip(_translate("MainWindow", "Create a new schematic"))
        self.action_newSchematic.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_options.setText(_translate("MainWindow", "Options"))
        self.action_options.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_showMajorGridPoints.setText(_translate("MainWindow", "Show major grid points"))
        self.action_showMinorGridPoints.setText(_translate("MainWindow", "Show minor grid points"))
        self.action_majorGridPointSpacing100.setText(_translate("MainWindow", "&100"))
        self.action_majorGridPointSpacing100.setToolTip(_translate("MainWindow", "Set the major grid point spacing to 100"))
        self.action_majorGridPointSpacing200.setText(_translate("MainWindow", "&200"))
        self.action_majorGridPointSpacing200.setToolTip(_translate("MainWindow", "Set the major grid point spacing to 200"))
        self.action_majorGridPointSpacing300.setText(_translate("MainWindow", "&300"))
        self.action_majorGridPointSpacing300.setToolTip(_translate("MainWindow", "Set the major grid point spacing to 300"))
        self.action_majorGridPointSpacing400.setText(_translate("MainWindow", "&400"))
        self.action_majorGridPointSpacing400.setToolTip(_translate("MainWindow", "Set the major grid point spacing to 400"))
        self.action_minorGridPointSpacing1.setText(_translate("MainWindow", "1"))
        self.action_minorGridPointSpacing1.setToolTip(_translate("MainWindow", "Set the minor grid point spacing to 1"))
        self.action_minorGridPointSpacing2.setText(_translate("MainWindow", "2"))
        self.action_minorGridPointSpacing2.setToolTip(_translate("MainWindow", "Set the minor grid point spacing to 2"))
        self.action_minorGridPointSpacing5.setText(_translate("MainWindow", "5"))
        self.action_minorGridPointSpacing5.setToolTip(_translate("MainWindow", "Set the minor grid point spacing to 5"))
        self.action_minorGridPointSpacing10.setText(_translate("MainWindow", "10"))
        self.action_minorGridPointSpacing10.setToolTip(_translate("MainWindow", "Set the minor grid point spacing to 10"))
        self.action_minorGridPointSpacing20.setText(_translate("MainWindow", "20"))
        self.action_minorGridPointSpacing20.setToolTip(_translate("MainWindow", "Set the minor grid point spacing to 20"))
        self.action_minorGridPointSpacing30.setText(_translate("MainWindow", "30"))
        self.action_minorGridPointSpacing30.setToolTip(_translate("MainWindow", "Set the minor grid point spacing to 30"))
        self.action_minorGridPointSpacing40.setText(_translate("MainWindow", "40"))
        self.action_minorGridPointSpacing40.setToolTip(_translate("MainWindow", "Set the minor grid point spacing to 40"))
        self.action_snapToGridSpacing1.setText(_translate("MainWindow", "1"))
        self.action_snapToGridSpacing1.setToolTip(_translate("MainWindow", "Snap the grid to a grid distance of 1"))
        self.action_snapToGridSpacing2.setText(_translate("MainWindow", "2"))
        self.action_snapToGridSpacing2.setToolTip(_translate("MainWindow", "Snap the grid to a grid distance of 2"))
        self.action_snapToGridSpacing5.setText(_translate("MainWindow", "5"))
        self.action_snapToGridSpacing5.setToolTip(_translate("MainWindow", "Snap the grid to a grid distance of 5"))
        self.action_snapToGridSpacing10.setText(_translate("MainWindow", "10"))
        self.action_snapToGridSpacing10.setToolTip(_translate("MainWindow", "Snap the grid to a grid distance of 10"))
        self.action_snapToGridSpacing20.setText(_translate("MainWindow", "20"))
        self.action_snapToGridSpacing20.setToolTip(_translate("MainWindow", "Snap the grid to a grid distance of 20"))
        self.action_snapToGridSpacing30.setText(_translate("MainWindow", "30"))
        self.action_snapToGridSpacing30.setToolTip(_translate("MainWindow", "Snap the grid to a grid distance of 30"))
        self.action_snapToGridSpacing40.setText(_translate("MainWindow", "40"))
        self.action_snapToGridSpacing40.setToolTip(_translate("MainWindow", "Snap the grid to a grid distance of 40"))
        self.action_setPenColourCustom.setText(_translate("MainWindow", "Cu&stom"))
        self.action_setPenColourCustom.setToolTip(_translate("MainWindow", "Set the colour of selected item(s) to a custom colour"))
        self.action_setBrushColourCustom.setText(_translate("MainWindow", "Cu&stom"))
        self.action_setBrushColourCustom.setToolTip(_translate("MainWindow", "Set the brush colour to a custom colour"))
        self.action_pickFont.setText(_translate("MainWindow", "&Font"))
        self.action_pickFont.setToolTip(_translate("MainWindow", "Pick font for creating new text items or for changing the font of selected text item(s)"))
        self.action_heightBringForward.setText(_translate("MainWindow", "Bring forward"))
        self.action_heightBringForward.setToolTip(_translate("MainWindow", "Brings selected item(s) forward"))
        self.action_heightBringForward.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.action_heightSendBack.setText(_translate("MainWindow", "Send back"))
        self.action_heightSendBack.setToolTip(_translate("MainWindow", "Sends selected item(s) back"))
        self.action_heightSendBack.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.action_heightReset.setText(_translate("MainWindow", "Reset"))
        self.action_heightReset.setToolTip(_translate("MainWindow", "Resets the height of the selected item(s)"))
        self.action_heightReset.setShortcut(_translate("MainWindow", "Ctrl+0"))
        self.action_escape.setText(_translate("MainWindow", "Cancel action"))
        self.action_escape.setIconText(_translate("MainWindow", "Cancel action"))
        self.action_escape.setToolTip(_translate("MainWindow", "Cancels any action being performed"))
        self.action_escape.setShortcut(_translate("MainWindow", "Esc"))
        self.action_group.setText(_translate("MainWindow", "Group"))
        self.action_group.setToolTip(_translate("MainWindow", "Group selected items together"))
        self.action_group.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.action_ungroup.setText(_translate("MainWindow", "Ungroup"))
        self.action_ungroup.setToolTip(_translate("MainWindow", "Disband the current group"))
        self.action_ungroup.setShortcut(_translate("MainWindow", "Ctrl+Shift+G"))
        self.action_updateYCircuit.setText(_translate("MainWindow", "Up&date"))
        self.action_updateYCircuit.setToolTip(_translate("MainWindow", "Update YCircuit to the latest version"))
        self.action_tutorialInverterSchematic.setText(_translate("MainWindow", "Inverter schematic"))
        self.action_tutorialInverterSchematic.setToolTip(_translate("MainWindow", "Open a tutorial in the web browser for creating a schematic"))
        self.action_tutorialCustomSymbols.setText(_translate("MainWindow", "Custom symbols"))
        self.action_tutorialCustomSymbols.setToolTip(_translate("MainWindow", "Open a tutorial in the web browser for creating custom symbols"))
        self.action_setWidthCustom.setText(_translate("MainWindow", "Cu&stom"))
        self.action_setWidthCustom.setToolTip(_translate("MainWindow", "Set the pen width to a custom integer value"))
        self.action_scale.setText(_translate("MainWindow", "Scale"))
        self.action_scale.setToolTip(_translate("MainWindow", "Change the scale of the selected item(s)"))
        self.action_paste.setText(_translate("MainWindow", "Paste"))
        self.action_paste.setToolTip(_translate("MainWindow", "Paste copied item(s) from the clipboard"))
        self.action_paste.setShortcut(_translate("MainWindow", "V"))
        self.action_addImage.setText(_translate("MainWindow", "Ima&ge"))
        self.action_addImage.setToolTip(_translate("MainWindow", "Import and embed an image"))
        self.action_importImage.setText(_translate("MainWindow", "Import image"))
        self.action_importImage.setToolTip(_translate("MainWindow", "Import and embed an image"))
        self.action_importImage.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.action_setPenJoinStyleRound.setText(_translate("MainWindow", "&Round"))
        self.action_setPenJoinStyleRound.setToolTip(_translate("MainWindow", "Set pen join style for selected item(s) to round (soft vertices)"))
        self.action_setPenJoinStyleMiter.setText(_translate("MainWindow", "Mi&ter"))
        self.action_setPenJoinStyleMiter.setToolTip(_translate("MainWindow", "Set pen join style for selected item(s) to miter (hard vertices)"))
        self.action_setPenJoinStyleBevel.setText(_translate("MainWindow", "&Bevel"))
        self.action_setPenJoinStyleBevel.setToolTip(_translate("MainWindow", "Set pen join style for selected item(s) to bevel"))
        self.action_setPenCapStyleSquare.setText(_translate("MainWindow", "&Square"))
        self.action_setPenCapStyleSquare.setToolTip(_translate("MainWindow", "Set the pen cap of the selected item(s) to square"))
        self.action_setPenCapStyleRound.setText(_translate("MainWindow", "&Round"))
        self.action_setPenCapStyleRound.setToolTip(_translate("MainWindow", "Set the pen cap of the selected item(s) to round"))
        self.action_setPenCapStyleFlat.setText(_translate("MainWindow", "&Flat"))
        self.action_setPenCapStyleFlat.setToolTip(_translate("MainWindow", "Set the pen cap of the selected item(s) to flat"))
        self.action_quickAddSymbol1.setText(_translate("MainWindow", "Symbol 1"))
        self.action_quickAddSymbol1.setToolTip(_translate("MainWindow", "Quick access to user-defined symbol. Choose the symbol to be loaded from the options menu."))
        self.action_quickAddSymbol1.setShortcut(_translate("MainWindow", "Ctrl+1"))
        self.action_quickAddSymbol2.setText(_translate("MainWindow", "Symbol 2"))
        self.action_quickAddSymbol2.setToolTip(_translate("MainWindow", "Quick access to user-defined symbol. Choose the symbol to be loaded from the options menu."))
        self.action_quickAddSymbol2.setShortcut(_translate("MainWindow", "Ctrl+2"))
        self.action_quickAddSymbol3.setText(_translate("MainWindow", "Symbol 3"))
        self.action_quickAddSymbol3.setToolTip(_translate("MainWindow", "Quick access to user-defined symbol. Choose the symbol to be loaded from the options menu."))
        self.action_quickAddSymbol3.setShortcut(_translate("MainWindow", "Ctrl+3"))
        self.action_quickAddSymbol4.setText(_translate("MainWindow", "Symbol 4"))
        self.action_quickAddSymbol4.setToolTip(_translate("MainWindow", "Quick access to user-defined symbol. Choose the symbol to be loaded from the options menu."))
        self.action_quickAddSymbol4.setShortcut(_translate("MainWindow", "Ctrl+4"))
        self.action_quickAddSymbol5.setText(_translate("MainWindow", "Symbol 5"))
        self.action_quickAddSymbol5.setToolTip(_translate("MainWindow", "Quick access to user-defined symbol. Choose the symbol to be loaded from the options menu."))
        self.action_quickAddSymbol5.setShortcut(_translate("MainWindow", "Ctrl+5"))
        self.action_showPins.setText(_translate("MainWindow", "Show pins"))
        self.action_showPins.setToolTip(_translate("MainWindow", "Toggle pin visibility (does not affect top level pins)"))
        self.action_showPins.setShortcut(_translate("MainWindow", "Shift+P"))
        self.action_addPin.setText(_translate("MainWindow", "Pin"))
        self.action_addPin.setShortcut(_translate("MainWindow", "P"))
        self.action_snapNetToPin.setText(_translate("MainWindow", "Snap net to pin"))
        self.action_snapNetToPin.setToolTip(_translate("MainWindow", "Snap net to nearest pin while drawing a net"))
        self.action_snapNetToPin.setShortcut(_translate("MainWindow", "S"))
        self.action_zoomIn.setText(_translate("MainWindow", "Zoom in"))
        self.action_zoomIn.setShortcut(_translate("MainWindow", "Z"))
        self.action_zoomOut.setText(_translate("MainWindow", "Zoom out"))
        self.action_zoomOut.setShortcut(_translate("MainWindow", "Shift+Z"))
        self.action_setScale.setText(_translate("MainWindow", "&Scale"))
        self.action_setScale.setToolTip(_translate("MainWindow", "Set the scale for the selected item(s)"))

from src.drawingarea import DrawingArea, DrawingAreaPreview
import icon_rc
