# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\gui\ycircuit_exportWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(575, 450)
        Dialog.setModal(True)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.doubleSpinBox_exportImageScaleFactor = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_exportImageScaleFactor.setEnabled(False)
        self.doubleSpinBox_exportImageScaleFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_exportImageScaleFactor.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_exportImageScaleFactor.setDecimals(1)
        self.doubleSpinBox_exportImageScaleFactor.setMinimum(1.0)
        self.doubleSpinBox_exportImageScaleFactor.setMaximum(4.0)
        self.doubleSpinBox_exportImageScaleFactor.setSingleStep(0.1)
        self.doubleSpinBox_exportImageScaleFactor.setProperty("value", 2.0)
        self.doubleSpinBox_exportImageScaleFactor.setObjectName("doubleSpinBox_exportImageScaleFactor")
        self.gridLayout_2.addWidget(self.doubleSpinBox_exportImageScaleFactor, 2, 1, 1, 1)
        self.doubleSpinBox_exportImageWhitespacePadding = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBox_exportImageWhitespacePadding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_exportImageWhitespacePadding.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_exportImageWhitespacePadding.setDecimals(1)
        self.doubleSpinBox_exportImageWhitespacePadding.setMinimum(1.0)
        self.doubleSpinBox_exportImageWhitespacePadding.setMaximum(4.0)
        self.doubleSpinBox_exportImageWhitespacePadding.setSingleStep(0.1)
        self.doubleSpinBox_exportImageWhitespacePadding.setProperty("value", 1.1)
        self.doubleSpinBox_exportImageWhitespacePadding.setObjectName("doubleSpinBox_exportImageWhitespacePadding")
        self.gridLayout_2.addWidget(self.doubleSpinBox_exportImageWhitespacePadding, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.comboBox_exportQuality = QtWidgets.QComboBox(Dialog)
        self.comboBox_exportQuality.setEnabled(False)
        self.comboBox_exportQuality.setObjectName("comboBox_exportQuality")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.comboBox_exportQuality.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_exportQuality, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_exportFormat = QtWidgets.QComboBox(Dialog)
        self.comboBox_exportFormat.setObjectName("comboBox_exportFormat")
        self.comboBox_exportFormat.addItem("")
        self.comboBox_exportFormat.addItem("")
        self.comboBox_exportFormat.addItem("")
        self.comboBox_exportFormat.addItem("")
        self.comboBox_exportFormat.addItem("")
        self.comboBox_exportFormat.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_exportFormat, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.checkBox_hidePins = QtWidgets.QCheckBox(Dialog)
        self.checkBox_hidePins.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_hidePins.setText("")
        self.checkBox_hidePins.setChecked(True)
        self.checkBox_hidePins.setObjectName("checkBox_hidePins")
        self.gridLayout_2.addWidget(self.checkBox_hidePins, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(27, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.graphicsView_exportPreview = DrawingAreaPreview(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_exportPreview.sizePolicy().hasHeightForWidth())
        self.graphicsView_exportPreview.setSizePolicy(sizePolicy)
        self.graphicsView_exportPreview.setMaximumSize(QtCore.QSize(300, 300))
        self.graphicsView_exportPreview.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graphicsView_exportPreview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_exportPreview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView_exportPreview.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.graphicsView_exportPreview.setInteractive(False)
        self.graphicsView_exportPreview.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsView_exportPreview.setCacheMode(QtWidgets.QGraphicsView.CacheBackground)
        self.graphicsView_exportPreview.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsView_exportPreview.setViewportUpdateMode(QtWidgets.QGraphicsView.BoundingRectViewportUpdate)
        self.graphicsView_exportPreview.setObjectName("graphicsView_exportPreview")
        self.horizontalLayout_3.addWidget(self.graphicsView_exportPreview)
        spacerItem6 = QtWidgets.QSpacerItem(27, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label_exportDimensions = QtWidgets.QLabel(Dialog)
        self.label_exportDimensions.setObjectName("label_exportDimensions")
        self.horizontalLayout.addWidget(self.label_exportDimensions, 0, QtCore.Qt.AlignHCenter)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_4.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.comboBox_exportQuality.setCurrentIndex(4)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.comboBox_exportFormat, self.doubleSpinBox_exportImageWhitespacePadding)
        Dialog.setTabOrder(self.doubleSpinBox_exportImageWhitespacePadding, self.doubleSpinBox_exportImageScaleFactor)
        Dialog.setTabOrder(self.doubleSpinBox_exportImageScaleFactor, self.comboBox_exportQuality)
        Dialog.setTabOrder(self.comboBox_exportQuality, self.checkBox_hidePins)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Export options"))
        self.label_4.setToolTip(_translate("Dialog", "Pick the quality of the export. Higher quality implies larger file sizes and vice versa."))
        self.label_4.setText(_translate("Dialog", "Quality:"))
        self.doubleSpinBox_exportImageScaleFactor.setToolTip(_translate("Dialog", "Sets the scaling factor of the exported image. You can tune this value to tradeoff speed of export with the resolution of the resultant images."))
        self.doubleSpinBox_exportImageWhitespacePadding.setToolTip(_translate("Dialog", "Sets the scaling factor of the overall exported image to the tight bounding box of elements within the scene. The difference between the two sizes is effectively the whitespace near the edges of the image."))
        self.label.setToolTip(_translate("Dialog", "Sets the scaling factor of the overall exported image to the tight bounding box of elements within the scene. The difference between the two sizes is effectively the whitespace near the edges of the image."))
        self.label.setText(_translate("Dialog", "Whitespace padding:"))
        self.label_2.setToolTip(_translate("Dialog", "Sets the scaling factor of the exported image. You can tune this value to tradeoff speed of export with the resolution of the resultant images."))
        self.label_2.setText(_translate("Dialog", "Scale factor:"))
        self.comboBox_exportQuality.setToolTip(_translate("Dialog", "Pick the quality of the export. Higher quality implies larger file sizes and vice versa."))
        self.comboBox_exportQuality.setItemText(0, _translate("Dialog", "10%"))
        self.comboBox_exportQuality.setItemText(1, _translate("Dialog", "20%"))
        self.comboBox_exportQuality.setItemText(2, _translate("Dialog", "30%"))
        self.comboBox_exportQuality.setItemText(3, _translate("Dialog", "40%"))
        self.comboBox_exportQuality.setItemText(4, _translate("Dialog", "50%"))
        self.comboBox_exportQuality.setItemText(5, _translate("Dialog", "60%"))
        self.comboBox_exportQuality.setItemText(6, _translate("Dialog", "70%"))
        self.comboBox_exportQuality.setItemText(7, _translate("Dialog", "80%"))
        self.comboBox_exportQuality.setItemText(8, _translate("Dialog", "90%"))
        self.comboBox_exportQuality.setItemText(9, _translate("Dialog", "100%"))
        self.label_3.setToolTip(_translate("Dialog", "Pick a default format for exporting to"))
        self.label_3.setText(_translate("Dialog", "Export format:"))
        self.comboBox_exportFormat.setToolTip(_translate("Dialog", "Pick a default format for exporting to"))
        self.comboBox_exportFormat.setItemText(0, _translate("Dialog", "PDF"))
        self.comboBox_exportFormat.setItemText(1, _translate("Dialog", "SVG"))
        self.comboBox_exportFormat.setItemText(2, _translate("Dialog", "PNG"))
        self.comboBox_exportFormat.setItemText(3, _translate("Dialog", "JPG"))
        self.comboBox_exportFormat.setItemText(4, _translate("Dialog", "BMP"))
        self.comboBox_exportFormat.setItemText(5, _translate("Dialog", "TIFF"))
        self.label_5.setToolTip(_translate("Dialog", "Hide the pins on symbols during export."))
        self.label_5.setText(_translate("Dialog", "Hide pins:"))
        self.checkBox_hidePins.setToolTip(_translate("Dialog", "Hide the pins on symbols during export."))
        self.label_exportDimensions.setText(_translate("Dialog", "4in x 4in"))

from src.preview import DrawingAreaPreview
