# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\gui\ycircuit_optionsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_printing = QtWidgets.QWidget()
        self.tab_printing.setObjectName("tab_printing")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_printing)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_printing)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_26 = QtWidgets.QLabel(self.groupBox_10)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_18.addWidget(self.label_26)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem)
        self.fontComboBox_fontFamily = QtWidgets.QFontComboBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.fontComboBox_fontFamily.setCurrentFont(font)
        self.fontComboBox_fontFamily.setObjectName("fontComboBox_fontFamily")
        self.horizontalLayout_18.addWidget(self.fontComboBox_fontFamily)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_27 = QtWidgets.QLabel(self.groupBox_10)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_19.addWidget(self.label_27)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.comboBox_fontPointSize = QtWidgets.QComboBox(self.groupBox_10)
        self.comboBox_fontPointSize.setObjectName("comboBox_fontPointSize")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.comboBox_fontPointSize.addItem("")
        self.horizontalLayout_19.addWidget(self.comboBox_fontPointSize)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.label_44 = QtWidgets.QLabel(self.groupBox_10)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_38.addWidget(self.label_44)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem2)
        self.checkBox_useEulerFontForLatex = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_useEulerFontForLatex.setText("")
        self.checkBox_useEulerFontForLatex.setObjectName("checkBox_useEulerFontForLatex")
        self.horizontalLayout_38.addWidget(self.checkBox_useEulerFontForLatex)
        self.verticalLayout_10.addLayout(self.horizontalLayout_38)
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.groupBox = QtWidgets.QGroupBox(self.tab_printing)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_penWidth = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_penWidth.setObjectName("comboBox_penWidth")
        self.comboBox_penWidth.addItem("")
        self.comboBox_penWidth.addItem("")
        self.comboBox_penWidth.addItem("")
        self.comboBox_penWidth.addItem("")
        self.comboBox_penWidth.addItem("")
        self.gridLayout.addWidget(self.comboBox_penWidth, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_penStyle = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_penStyle.setObjectName("comboBox_penStyle")
        self.comboBox_penStyle.addItem("")
        self.comboBox_penStyle.addItem("")
        self.comboBox_penStyle.addItem("")
        self.comboBox_penStyle.addItem("")
        self.comboBox_penStyle.addItem("")
        self.gridLayout.addWidget(self.comboBox_penStyle, 2, 2, 1, 1)
        self.comboBox_penColour = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_penColour.setObjectName("comboBox_penColour")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.gridLayout.addWidget(self.comboBox_penColour, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 4, 1, 1, 1)
        self.comboBox_penJoinStyle = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_penJoinStyle.setObjectName("comboBox_penJoinStyle")
        self.comboBox_penJoinStyle.addItem("")
        self.comboBox_penJoinStyle.addItem("")
        self.comboBox_penJoinStyle.addItem("")
        self.gridLayout.addWidget(self.comboBox_penJoinStyle, 4, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.groupBox)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 3, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 3, 1, 1, 1)
        self.comboBox_penCapStyle = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_penCapStyle.setObjectName("comboBox_penCapStyle")
        self.comboBox_penCapStyle.addItem("")
        self.comboBox_penCapStyle.addItem("")
        self.comboBox_penCapStyle.addItem("")
        self.gridLayout.addWidget(self.comboBox_penCapStyle, 3, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_printing)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        self.comboBox_brushColour = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_brushColour.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_brushColour.setObjectName("comboBox_brushColour")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_brushColour, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 1, 1, 1, 1)
        self.comboBox_brushStyle = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_brushStyle.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_brushStyle.setObjectName("comboBox_brushStyle")
        self.comboBox_brushStyle.addItem("")
        self.comboBox_brushStyle.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_brushStyle, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_printing)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_22 = QtWidgets.QLabel(self.groupBox_8)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.comboBox_rotationDirection = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_rotationDirection.setObjectName("comboBox_rotationDirection")
        self.comboBox_rotationDirection.addItem("")
        self.comboBox_rotationDirection.addItem("")
        self.horizontalLayout_14.addWidget(self.comboBox_rotationDirection)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.spinBox_rotationAngle = QtWidgets.QSpinBox(self.groupBox_8)
        self.spinBox_rotationAngle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_rotationAngle.setMinimum(1)
        self.spinBox_rotationAngle.setMaximum(180)
        self.spinBox_rotationAngle.setSingleStep(15)
        self.spinBox_rotationAngle.setProperty("value", 45)
        self.spinBox_rotationAngle.setObjectName("spinBox_rotationAngle")
        self.horizontalLayout_15.addWidget(self.spinBox_rotationAngle)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.verticalLayout_4.addWidget(self.groupBox_8)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem12)
        self.tabWidget.addTab(self.tab_printing, "")
        self.tab_grid = QtWidgets.QWidget()
        self.tab_grid.setObjectName("tab_grid")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_grid)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.tab_grid)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.checkBox_gridVisibility = QtWidgets.QCheckBox(self.tab_grid)
        self.checkBox_gridVisibility.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_gridVisibility.setText("")
        self.checkBox_gridVisibility.setObjectName("checkBox_gridVisibility")
        self.horizontalLayout_5.addWidget(self.checkBox_gridVisibility)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_grid)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem14, 0, 1, 1, 1)
        self.checkBox_gridSnapToGrid = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_gridSnapToGrid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_gridSnapToGrid.setText("")
        self.checkBox_gridSnapToGrid.setObjectName("checkBox_gridSnapToGrid")
        self.gridLayout_2.addWidget(self.checkBox_gridSnapToGrid, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 1, 1, 1, 1)
        self.comboBox_gridSnapToGridSpacing = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_gridSnapToGridSpacing.setObjectName("comboBox_gridSnapToGridSpacing")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_gridSnapToGridSpacing, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_grid)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem16, 0, 1, 1, 1)
        self.checkBox_gridShowMajorGridPoints = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_gridShowMajorGridPoints.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_gridShowMajorGridPoints.setText("")
        self.checkBox_gridShowMajorGridPoints.setObjectName("checkBox_gridShowMajorGridPoints")
        self.gridLayout_4.addWidget(self.checkBox_gridShowMajorGridPoints, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem17, 1, 1, 1, 1)
        self.comboBox_gridMajorGridPointSpacing = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_gridMajorGridPointSpacing.setObjectName("comboBox_gridMajorGridPointSpacing")
        self.comboBox_gridMajorGridPointSpacing.addItem("")
        self.comboBox_gridMajorGridPointSpacing.addItem("")
        self.comboBox_gridMajorGridPointSpacing.addItem("")
        self.comboBox_gridMajorGridPointSpacing.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_gridMajorGridPointSpacing, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem18, 2, 1, 1, 1)
        self.checkBox_gridShowMinorGridPoints = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_gridShowMinorGridPoints.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_gridShowMinorGridPoints.setText("")
        self.checkBox_gridShowMinorGridPoints.setObjectName("checkBox_gridShowMinorGridPoints")
        self.gridLayout_4.addWidget(self.checkBox_gridShowMinorGridPoints, 2, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 3, 1, 1, 1)
        self.comboBox_gridMinorGridPointSpacing = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_gridMinorGridPointSpacing.setObjectName("comboBox_gridMinorGridPointSpacing")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_gridMinorGridPointSpacing, 3, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_4)
        spacerItem20 = QtWidgets.QSpacerItem(20, 184, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem20)
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.tabWidget.addTab(self.tab_grid, "")
        self.tab_saveExport = QtWidgets.QWidget()
        self.tab_saveExport.setObjectName("tab_saveExport")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_saveExport)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_saveExport)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_17.addWidget(self.label_24)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem21)
        self.checkBox_autobackupEnable = QtWidgets.QCheckBox(self.groupBox_9)
        self.checkBox_autobackupEnable.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_autobackupEnable.setText("")
        self.checkBox_autobackupEnable.setChecked(True)
        self.checkBox_autobackupEnable.setObjectName("checkBox_autobackupEnable")
        self.horizontalLayout_17.addWidget(self.checkBox_autobackupEnable)
        self.verticalLayout_9.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_25 = QtWidgets.QLabel(self.groupBox_9)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_16.addWidget(self.label_25)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.spinBox_autobackupTimerInterval = QtWidgets.QSpinBox(self.groupBox_9)
        self.spinBox_autobackupTimerInterval.setSuffix("")
        self.spinBox_autobackupTimerInterval.setMinimum(1)
        self.spinBox_autobackupTimerInterval.setMaximum(6000)
        self.spinBox_autobackupTimerInterval.setSingleStep(10)
        self.spinBox_autobackupTimerInterval.setProperty("value", 10)
        self.spinBox_autobackupTimerInterval.setObjectName("spinBox_autobackupTimerInterval")
        self.horizontalLayout_16.addWidget(self.spinBox_autobackupTimerInterval)
        self.verticalLayout_9.addLayout(self.horizontalLayout_16)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_saveExport)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem23)
        self.checkBox_showSchematicPreview = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_showSchematicPreview.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_showSchematicPreview.setText("")
        self.checkBox_showSchematicPreview.setChecked(True)
        self.checkBox_showSchematicPreview.setObjectName("checkBox_showSchematicPreview")
        self.horizontalLayout_6.addWidget(self.checkBox_showSchematicPreview)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_7.addWidget(self.label_15)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem24)
        self.lineEdit_defaultSchematicSaveFolder = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_defaultSchematicSaveFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_defaultSchematicSaveFolder.setReadOnly(True)
        self.lineEdit_defaultSchematicSaveFolder.setObjectName("lineEdit_defaultSchematicSaveFolder")
        self.horizontalLayout_7.addWidget(self.lineEdit_defaultSchematicSaveFolder)
        self.pushButton_defaultSchematicSaveFolder = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_defaultSchematicSaveFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_defaultSchematicSaveFolder.setObjectName("pushButton_defaultSchematicSaveFolder")
        self.horizontalLayout_7.addWidget(self.pushButton_defaultSchematicSaveFolder)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_saveExport)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem25)
        self.checkBox_showSymbolPreview = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_showSymbolPreview.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_showSymbolPreview.setText("")
        self.checkBox_showSymbolPreview.setChecked(True)
        self.checkBox_showSymbolPreview.setObjectName("checkBox_showSymbolPreview")
        self.horizontalLayout_8.addWidget(self.checkBox_showSymbolPreview)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem26)
        self.lineEdit_defaultSymbolSaveFolder = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_defaultSymbolSaveFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_defaultSymbolSaveFolder.setReadOnly(True)
        self.lineEdit_defaultSymbolSaveFolder.setObjectName("lineEdit_defaultSymbolSaveFolder")
        self.horizontalLayout_9.addWidget(self.lineEdit_defaultSymbolSaveFolder)
        self.pushButton_defaultSymbolSaveFolder = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_defaultSymbolSaveFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_defaultSymbolSaveFolder.setObjectName("pushButton_defaultSymbolSaveFolder")
        self.horizontalLayout_9.addWidget(self.pushButton_defaultSymbolSaveFolder)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_saveExport)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_10.addWidget(self.label_18)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem27)
        self.comboBox_defaultExportFormat = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_defaultExportFormat.setObjectName("comboBox_defaultExportFormat")
        self.comboBox_defaultExportFormat.addItem("")
        self.comboBox_defaultExportFormat.addItem("")
        self.comboBox_defaultExportFormat.addItem("")
        self.comboBox_defaultExportFormat.addItem("")
        self.comboBox_defaultExportFormat.addItem("")
        self.comboBox_defaultExportFormat.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_defaultExportFormat)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_11.addWidget(self.label_19)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem28)
        self.lineEdit_defaultExportFolder = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_defaultExportFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_defaultExportFolder.setReadOnly(True)
        self.lineEdit_defaultExportFolder.setObjectName("lineEdit_defaultExportFolder")
        self.horizontalLayout_11.addWidget(self.lineEdit_defaultExportFolder)
        self.pushButton_defaultExportFolder = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_defaultExportFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_defaultExportFolder.setObjectName("pushButton_defaultExportFolder")
        self.horizontalLayout_11.addWidget(self.pushButton_defaultExportFolder)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_12.addWidget(self.label_20)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem29)
        self.doubleSpinBox_exportImageWhitespacePadding = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_exportImageWhitespacePadding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_exportImageWhitespacePadding.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_exportImageWhitespacePadding.setDecimals(1)
        self.doubleSpinBox_exportImageWhitespacePadding.setMinimum(1.0)
        self.doubleSpinBox_exportImageWhitespacePadding.setMaximum(4.0)
        self.doubleSpinBox_exportImageWhitespacePadding.setSingleStep(0.1)
        self.doubleSpinBox_exportImageWhitespacePadding.setProperty("value", 1.1)
        self.doubleSpinBox_exportImageWhitespacePadding.setObjectName("doubleSpinBox_exportImageWhitespacePadding")
        self.horizontalLayout_12.addWidget(self.doubleSpinBox_exportImageWhitespacePadding)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem30)
        self.doubleSpinBox_exportImageScaleFactor = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.doubleSpinBox_exportImageScaleFactor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_exportImageScaleFactor.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_exportImageScaleFactor.setDecimals(1)
        self.doubleSpinBox_exportImageScaleFactor.setMinimum(1.0)
        self.doubleSpinBox_exportImageScaleFactor.setMaximum(4.0)
        self.doubleSpinBox_exportImageScaleFactor.setSingleStep(0.1)
        self.doubleSpinBox_exportImageScaleFactor.setProperty("value", 2.0)
        self.doubleSpinBox_exportImageScaleFactor.setObjectName("doubleSpinBox_exportImageScaleFactor")
        self.horizontalLayout_13.addWidget(self.doubleSpinBox_exportImageScaleFactor)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        spacerItem31 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem31)
        self.tabWidget.addTab(self.tab_saveExport, "")
        self.tab_mouse = QtWidgets.QWidget()
        self.tab_mouse.setObjectName("tab_mouse")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tab_mouse)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_29 = QtWidgets.QLabel(self.tab_mouse)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_21.addWidget(self.label_29)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem32)
        self.checkBox_showMouseRect = QtWidgets.QCheckBox(self.tab_mouse)
        self.checkBox_showMouseRect.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_showMouseRect.setText("")
        self.checkBox_showMouseRect.setChecked(True)
        self.checkBox_showMouseRect.setObjectName("checkBox_showMouseRect")
        self.horizontalLayout_21.addWidget(self.checkBox_showMouseRect)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_mouse)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_30 = QtWidgets.QLabel(self.groupBox_11)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_22.addWidget(self.label_30)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem33)
        self.checkBox_showAnimationPan = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_showAnimationPan.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_showAnimationPan.setText("")
        self.checkBox_showAnimationPan.setChecked(True)
        self.checkBox_showAnimationPan.setObjectName("checkBox_showAnimationPan")
        self.horizontalLayout_22.addWidget(self.checkBox_showAnimationPan)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_31 = QtWidgets.QLabel(self.groupBox_11)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_23.addWidget(self.label_31)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem34)
        self.checkBox_showAnimationZoom = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_showAnimationZoom.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_showAnimationZoom.setText("")
        self.checkBox_showAnimationZoom.setChecked(True)
        self.checkBox_showAnimationZoom.setObjectName("checkBox_showAnimationZoom")
        self.horizontalLayout_23.addWidget(self.checkBox_showAnimationZoom)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.verticalLayout_11.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_mouse)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_32 = QtWidgets.QLabel(self.groupBox_12)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_24.addWidget(self.label_32)
        spacerItem35 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem35)
        self.comboBox_scrollModifierNone = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_scrollModifierNone.setObjectName("comboBox_scrollModifierNone")
        self.comboBox_scrollModifierNone.addItem("")
        self.comboBox_scrollModifierNone.addItem("")
        self.comboBox_scrollModifierNone.addItem("")
        self.horizontalLayout_24.addWidget(self.comboBox_scrollModifierNone)
        self.verticalLayout_13.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_33 = QtWidgets.QLabel(self.groupBox_12)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_25.addWidget(self.label_33)
        spacerItem36 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem36)
        self.comboBox_scrollModifierCtrl = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_scrollModifierCtrl.setObjectName("comboBox_scrollModifierCtrl")
        self.comboBox_scrollModifierCtrl.addItem("")
        self.comboBox_scrollModifierCtrl.addItem("")
        self.comboBox_scrollModifierCtrl.addItem("")
        self.horizontalLayout_25.addWidget(self.comboBox_scrollModifierCtrl)
        self.verticalLayout_13.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_34 = QtWidgets.QLabel(self.groupBox_12)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_26.addWidget(self.label_34)
        spacerItem37 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem37)
        self.comboBox_scrollModifierShift = QtWidgets.QComboBox(self.groupBox_12)
        self.comboBox_scrollModifierShift.setObjectName("comboBox_scrollModifierShift")
        self.comboBox_scrollModifierShift.addItem("")
        self.comboBox_scrollModifierShift.addItem("")
        self.comboBox_scrollModifierShift.addItem("")
        self.horizontalLayout_26.addWidget(self.comboBox_scrollModifierShift)
        self.verticalLayout_13.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_35 = QtWidgets.QLabel(self.groupBox_12)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_27.addWidget(self.label_35)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem38)
        self.checkBox_zoomInvert = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_zoomInvert.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_zoomInvert.setText("")
        self.checkBox_zoomInvert.setObjectName("checkBox_zoomInvert")
        self.horizontalLayout_27.addWidget(self.checkBox_zoomInvert)
        self.verticalLayout_13.addLayout(self.horizontalLayout_27)
        self.verticalLayout_11.addWidget(self.groupBox_12)
        spacerItem39 = QtWidgets.QSpacerItem(20, 195, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem39)
        self.tabWidget.addTab(self.tab_mouse, "")
        self.tab_shortcuts = QtWidgets.QWidget()
        self.tab_shortcuts.setObjectName("tab_shortcuts")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.tab_shortcuts)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.tableView_shortcuts = QtWidgets.QTableView(self.tab_shortcuts)
        self.tableView_shortcuts.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableView_shortcuts.setTabKeyNavigation(False)
        self.tableView_shortcuts.setAlternatingRowColors(True)
        self.tableView_shortcuts.setObjectName("tableView_shortcuts")
        self.tableView_shortcuts.horizontalHeader().setStretchLastSection(True)
        self.tableView_shortcuts.verticalHeader().setVisible(False)
        self.horizontalLayout_28.addWidget(self.tableView_shortcuts)
        self.tabWidget.addTab(self.tab_shortcuts, "")
        self.tab_misc = QtWidgets.QWidget()
        self.tab_misc.setObjectName("tab_misc")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.tab_misc)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_misc)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_38 = QtWidgets.QLabel(self.groupBox_13)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_29.addWidget(self.label_38)
        spacerItem40 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem40)
        self.lineEdit_quickAddSymbol1 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_quickAddSymbol1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_quickAddSymbol1.setReadOnly(True)
        self.lineEdit_quickAddSymbol1.setObjectName("lineEdit_quickAddSymbol1")
        self.horizontalLayout_29.addWidget(self.lineEdit_quickAddSymbol1)
        self.pushButton_quickAddSymbol1 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_quickAddSymbol1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_quickAddSymbol1.setObjectName("pushButton_quickAddSymbol1")
        self.horizontalLayout_29.addWidget(self.pushButton_quickAddSymbol1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_39 = QtWidgets.QLabel(self.groupBox_13)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_30.addWidget(self.label_39)
        spacerItem41 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem41)
        self.lineEdit_quickAddSymbol2 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_quickAddSymbol2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_quickAddSymbol2.setReadOnly(True)
        self.lineEdit_quickAddSymbol2.setObjectName("lineEdit_quickAddSymbol2")
        self.horizontalLayout_30.addWidget(self.lineEdit_quickAddSymbol2)
        self.pushButton_quickAddSymbol2 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_quickAddSymbol2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_quickAddSymbol2.setObjectName("pushButton_quickAddSymbol2")
        self.horizontalLayout_30.addWidget(self.pushButton_quickAddSymbol2)
        self.verticalLayout_15.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_40 = QtWidgets.QLabel(self.groupBox_13)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_31.addWidget(self.label_40)
        spacerItem42 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem42)
        self.lineEdit_quickAddSymbol3 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_quickAddSymbol3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_quickAddSymbol3.setReadOnly(True)
        self.lineEdit_quickAddSymbol3.setObjectName("lineEdit_quickAddSymbol3")
        self.horizontalLayout_31.addWidget(self.lineEdit_quickAddSymbol3)
        self.pushButton_quickAddSymbol3 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_quickAddSymbol3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_quickAddSymbol3.setObjectName("pushButton_quickAddSymbol3")
        self.horizontalLayout_31.addWidget(self.pushButton_quickAddSymbol3)
        self.verticalLayout_15.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.label_41 = QtWidgets.QLabel(self.groupBox_13)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_32.addWidget(self.label_41)
        spacerItem43 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem43)
        self.lineEdit_quickAddSymbol4 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_quickAddSymbol4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_quickAddSymbol4.setReadOnly(True)
        self.lineEdit_quickAddSymbol4.setObjectName("lineEdit_quickAddSymbol4")
        self.horizontalLayout_32.addWidget(self.lineEdit_quickAddSymbol4)
        self.pushButton_quickAddSymbol4 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_quickAddSymbol4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_quickAddSymbol4.setObjectName("pushButton_quickAddSymbol4")
        self.horizontalLayout_32.addWidget(self.pushButton_quickAddSymbol4)
        self.verticalLayout_15.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_42 = QtWidgets.QLabel(self.groupBox_13)
        self.label_42.setObjectName("label_42")
        self.horizontalLayout_33.addWidget(self.label_42)
        spacerItem44 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem44)
        self.lineEdit_quickAddSymbol5 = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_quickAddSymbol5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_quickAddSymbol5.setReadOnly(True)
        self.lineEdit_quickAddSymbol5.setObjectName("lineEdit_quickAddSymbol5")
        self.horizontalLayout_33.addWidget(self.lineEdit_quickAddSymbol5)
        self.pushButton_quickAddSymbol5 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_quickAddSymbol5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_quickAddSymbol5.setObjectName("pushButton_quickAddSymbol5")
        self.horizontalLayout_33.addWidget(self.pushButton_quickAddSymbol5)
        self.verticalLayout_15.addLayout(self.horizontalLayout_33)
        self.verticalLayout_17.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_misc)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_28 = QtWidgets.QLabel(self.groupBox_14)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_20.addWidget(self.label_28)
        spacerItem45 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem45)
        self.lineEdit_defaultSymbolPreviewFolder = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_defaultSymbolPreviewFolder.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_defaultSymbolPreviewFolder.setReadOnly(True)
        self.lineEdit_defaultSymbolPreviewFolder.setObjectName("lineEdit_defaultSymbolPreviewFolder")
        self.horizontalLayout_20.addWidget(self.lineEdit_defaultSymbolPreviewFolder)
        self.pushButton_defaultSymbolPreviewFolder = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_defaultSymbolPreviewFolder.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_defaultSymbolPreviewFolder.setObjectName("pushButton_defaultSymbolPreviewFolder")
        self.horizontalLayout_20.addWidget(self.pushButton_defaultSymbolPreviewFolder)
        self.verticalLayout_16.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_43 = QtWidgets.QLabel(self.groupBox_14)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_34.addWidget(self.label_43)
        spacerItem46 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem46)
        self.lineEdit_symbolPreviewFolder1 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_symbolPreviewFolder1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_symbolPreviewFolder1.setReadOnly(True)
        self.lineEdit_symbolPreviewFolder1.setObjectName("lineEdit_symbolPreviewFolder1")
        self.horizontalLayout_34.addWidget(self.lineEdit_symbolPreviewFolder1)
        self.pushButton_symbolPreviewFolder1 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_symbolPreviewFolder1.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_symbolPreviewFolder1.setObjectName("pushButton_symbolPreviewFolder1")
        self.horizontalLayout_34.addWidget(self.pushButton_symbolPreviewFolder1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_45 = QtWidgets.QLabel(self.groupBox_14)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_36.addWidget(self.label_45)
        spacerItem47 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem47)
        self.lineEdit_symbolPreviewFolder2 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_symbolPreviewFolder2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_symbolPreviewFolder2.setReadOnly(True)
        self.lineEdit_symbolPreviewFolder2.setObjectName("lineEdit_symbolPreviewFolder2")
        self.horizontalLayout_36.addWidget(self.lineEdit_symbolPreviewFolder2)
        self.pushButton_symbolPreviewFolder2 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_symbolPreviewFolder2.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_symbolPreviewFolder2.setObjectName("pushButton_symbolPreviewFolder2")
        self.horizontalLayout_36.addWidget(self.pushButton_symbolPreviewFolder2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_46 = QtWidgets.QLabel(self.groupBox_14)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_37.addWidget(self.label_46)
        spacerItem48 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem48)
        self.lineEdit_symbolPreviewFolder3 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_symbolPreviewFolder3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_symbolPreviewFolder3.setReadOnly(True)
        self.lineEdit_symbolPreviewFolder3.setObjectName("lineEdit_symbolPreviewFolder3")
        self.horizontalLayout_37.addWidget(self.lineEdit_symbolPreviewFolder3)
        self.pushButton_symbolPreviewFolder3 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_symbolPreviewFolder3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButton_symbolPreviewFolder3.setObjectName("pushButton_symbolPreviewFolder3")
        self.horizontalLayout_37.addWidget(self.pushButton_symbolPreviewFolder3)
        self.verticalLayout_16.addLayout(self.horizontalLayout_37)
        self.verticalLayout_17.addWidget(self.groupBox_14)
        spacerItem49 = QtWidgets.QSpacerItem(20, 257, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem49)
        self.tabWidget.addTab(self.tab_misc, "")
        self.verticalLayout_14.addWidget(self.tabWidget)
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_14.addWidget(self.label_4)
        spacerItem50 = QtWidgets.QSpacerItem(20, 307, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem50)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem51 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem51)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_14.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_penWidth.setCurrentIndex(1)
        self.comboBox_penStyle.setCurrentIndex(0)
        self.comboBox_penColour.setCurrentIndex(0)
        self.comboBox_brushColour.setCurrentIndex(0)
        self.comboBox_brushStyle.setCurrentIndex(0)
        self.comboBox_gridSnapToGridSpacing.setCurrentIndex(3)
        self.comboBox_gridMinorGridPointSpacing.setCurrentIndex(4)
        self.comboBox_scrollModifierCtrl.setCurrentIndex(1)
        self.comboBox_scrollModifierShift.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.groupBox_10.setTitle(_translate("Dialog", "Font"))
        self.label_26.setText(_translate("Dialog", "Default font family"))
        self.fontComboBox_fontFamily.setToolTip(_translate("Dialog", "Set the default font family"))
        self.label_27.setText(_translate("Dialog", "Default font size"))
        self.comboBox_fontPointSize.setToolTip(_translate("Dialog", "Set the default font size"))
        self.comboBox_fontPointSize.setCurrentText(_translate("Dialog", "6"))
        self.comboBox_fontPointSize.setItemText(0, _translate("Dialog", "6"))
        self.comboBox_fontPointSize.setItemText(1, _translate("Dialog", "7"))
        self.comboBox_fontPointSize.setItemText(2, _translate("Dialog", "8"))
        self.comboBox_fontPointSize.setItemText(3, _translate("Dialog", "9"))
        self.comboBox_fontPointSize.setItemText(4, _translate("Dialog", "10"))
        self.comboBox_fontPointSize.setItemText(5, _translate("Dialog", "11"))
        self.comboBox_fontPointSize.setItemText(6, _translate("Dialog", "12"))
        self.comboBox_fontPointSize.setItemText(7, _translate("Dialog", "14"))
        self.comboBox_fontPointSize.setItemText(8, _translate("Dialog", "16"))
        self.comboBox_fontPointSize.setItemText(9, _translate("Dialog", "18"))
        self.comboBox_fontPointSize.setItemText(10, _translate("Dialog", "20"))
        self.comboBox_fontPointSize.setItemText(11, _translate("Dialog", "22"))
        self.comboBox_fontPointSize.setItemText(12, _translate("Dialog", "24"))
        self.comboBox_fontPointSize.setItemText(13, _translate("Dialog", "26"))
        self.comboBox_fontPointSize.setItemText(14, _translate("Dialog", "28"))
        self.comboBox_fontPointSize.setItemText(15, _translate("Dialog", "36"))
        self.comboBox_fontPointSize.setItemText(16, _translate("Dialog", "48"))
        self.comboBox_fontPointSize.setItemText(17, _translate("Dialog", "72"))
        self.label_44.setText(_translate("Dialog", "Use Euler font for LaTeX"))
        self.groupBox.setTitle(_translate("Dialog", "Pen"))
        self.label_2.setText(_translate("Dialog", "Default colour"))
        self.comboBox_penWidth.setToolTip(_translate("Dialog", "Set the default width of the pen for drawing items"))
        self.comboBox_penWidth.setItemText(0, _translate("Dialog", "2"))
        self.comboBox_penWidth.setItemText(1, _translate("Dialog", "4"))
        self.comboBox_penWidth.setItemText(2, _translate("Dialog", "6"))
        self.comboBox_penWidth.setItemText(3, _translate("Dialog", "8"))
        self.comboBox_penWidth.setItemText(4, _translate("Dialog", "10"))
        self.label_3.setText(_translate("Dialog", "Default style"))
        self.comboBox_penStyle.setToolTip(_translate("Dialog", "Set the default style of the pen for drawing items"))
        self.comboBox_penStyle.setItemText(0, _translate("Dialog", "Solid"))
        self.comboBox_penStyle.setItemText(1, _translate("Dialog", "Dash"))
        self.comboBox_penStyle.setItemText(2, _translate("Dialog", "Dot"))
        self.comboBox_penStyle.setItemText(3, _translate("Dialog", "Dash-dot"))
        self.comboBox_penStyle.setItemText(4, _translate("Dialog", "Dash-dot-dot"))
        self.comboBox_penColour.setToolTip(_translate("Dialog", "Set the default colour of the pen for drawing items"))
        self.comboBox_penColour.setItemText(0, _translate("Dialog", "Black"))
        self.comboBox_penColour.setItemText(1, _translate("Dialog", "Red"))
        self.comboBox_penColour.setItemText(2, _translate("Dialog", "Blue"))
        self.comboBox_penColour.setItemText(3, _translate("Dialog", "Green"))
        self.comboBox_penColour.setItemText(4, _translate("Dialog", "Cyan"))
        self.comboBox_penColour.setItemText(5, _translate("Dialog", "Magenta"))
        self.comboBox_penColour.setItemText(6, _translate("Dialog", "Yellow"))
        self.label.setText(_translate("Dialog", "Default width"))
        self.label_36.setText(_translate("Dialog", "Default join style"))
        self.comboBox_penJoinStyle.setToolTip(_translate("Dialog", "Set the default join style of the pen for drawing items"))
        self.comboBox_penJoinStyle.setItemText(0, _translate("Dialog", "Round"))
        self.comboBox_penJoinStyle.setItemText(1, _translate("Dialog", "Miter"))
        self.comboBox_penJoinStyle.setItemText(2, _translate("Dialog", "Bevel"))
        self.label_37.setText(_translate("Dialog", "Default cap style"))
        self.comboBox_penCapStyle.setToolTip(_translate("Dialog", "Set the default cap style of the pen for drawing items"))
        self.comboBox_penCapStyle.setItemText(0, _translate("Dialog", "Square"))
        self.comboBox_penCapStyle.setItemText(1, _translate("Dialog", "Round"))
        self.comboBox_penCapStyle.setItemText(2, _translate("Dialog", "Flat"))
        self.groupBox_2.setTitle(_translate("Dialog", "Brush"))
        self.label_9.setText(_translate("Dialog", "Default colour"))
        self.comboBox_brushColour.setToolTip(_translate("Dialog", "Set the default colour of the brush for drawing items"))
        self.comboBox_brushColour.setItemText(0, _translate("Dialog", "Black"))
        self.comboBox_brushColour.setItemText(1, _translate("Dialog", "Red"))
        self.comboBox_brushColour.setItemText(2, _translate("Dialog", "Blue"))
        self.comboBox_brushColour.setItemText(3, _translate("Dialog", "Green"))
        self.comboBox_brushColour.setItemText(4, _translate("Dialog", "Cyan"))
        self.comboBox_brushColour.setItemText(5, _translate("Dialog", "Magenta"))
        self.comboBox_brushColour.setItemText(6, _translate("Dialog", "Yellow"))
        self.label_10.setText(_translate("Dialog", "Default style"))
        self.comboBox_brushStyle.setToolTip(_translate("Dialog", "Set the default style of the brush for drawing items"))
        self.comboBox_brushStyle.setItemText(0, _translate("Dialog", "No fill"))
        self.comboBox_brushStyle.setItemText(1, _translate("Dialog", "Solid"))
        self.groupBox_8.setTitle(_translate("Dialog", "Rotation"))
        self.label_22.setText(_translate("Dialog", "Direction"))
        self.comboBox_rotationDirection.setToolTip(_translate("Dialog", "Set the default rotation direction to clockwise or counter-clockwise"))
        self.comboBox_rotationDirection.setItemText(0, _translate("Dialog", "Clockwise"))
        self.comboBox_rotationDirection.setItemText(1, _translate("Dialog", "Counter-clockwise"))
        self.label_23.setText(_translate("Dialog", "Angle"))
        self.spinBox_rotationAngle.setToolTip(_translate("Dialog", "Set the default angle by which to rotate items"))
        self.spinBox_rotationAngle.setSuffix(_translate("Dialog", "°"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_printing), _translate("Dialog", "Painting"))
        self.label_11.setText(_translate("Dialog", "Visibility"))
        self.checkBox_gridVisibility.setToolTip(_translate("Dialog", "Toggle default grid visibility"))
        self.groupBox_3.setTitle(_translate("Dialog", "Snapping"))
        self.label_14.setText(_translate("Dialog", "Snap to grid"))
        self.checkBox_gridSnapToGrid.setToolTip(_translate("Dialog", "Toggle default snapping to grid"))
        self.label_7.setText(_translate("Dialog", "Snap to grid spacing"))
        self.comboBox_gridSnapToGridSpacing.setToolTip(_translate("Dialog", "Set the default grid size to use for snapping"))
        self.comboBox_gridSnapToGridSpacing.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_gridSnapToGridSpacing.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_gridSnapToGridSpacing.setItemText(2, _translate("Dialog", "5"))
        self.comboBox_gridSnapToGridSpacing.setItemText(3, _translate("Dialog", "10"))
        self.comboBox_gridSnapToGridSpacing.setItemText(4, _translate("Dialog", "20"))
        self.comboBox_gridSnapToGridSpacing.setItemText(5, _translate("Dialog", "30"))
        self.comboBox_gridSnapToGridSpacing.setItemText(6, _translate("Dialog", "40"))
        self.groupBox_4.setTitle(_translate("Dialog", "Major and minor points"))
        self.label_12.setText(_translate("Dialog", "Show major grid points"))
        self.checkBox_gridShowMajorGridPoints.setToolTip(_translate("Dialog", "Toggle default visibility of the major grid points"))
        self.label_13.setText(_translate("Dialog", "Major grid point spacing"))
        self.comboBox_gridMajorGridPointSpacing.setToolTip(_translate("Dialog", "Toggle default spacing of the major grid points"))
        self.comboBox_gridMajorGridPointSpacing.setItemText(0, _translate("Dialog", "100"))
        self.comboBox_gridMajorGridPointSpacing.setItemText(1, _translate("Dialog", "200"))
        self.comboBox_gridMajorGridPointSpacing.setItemText(2, _translate("Dialog", "300"))
        self.comboBox_gridMajorGridPointSpacing.setItemText(3, _translate("Dialog", "400"))
        self.label_6.setText(_translate("Dialog", "Show minor grid points"))
        self.checkBox_gridShowMinorGridPoints.setToolTip(_translate("Dialog", "Toggle default visibility of the minor grid points"))
        self.label_5.setText(_translate("Dialog", "Minor grid point spacing"))
        self.comboBox_gridMinorGridPointSpacing.setToolTip(_translate("Dialog", "Toggle default spacing of the minor grid points"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(2, _translate("Dialog", "5"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(3, _translate("Dialog", "10"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(4, _translate("Dialog", "20"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(5, _translate("Dialog", "30"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(6, _translate("Dialog", "40"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_grid), _translate("Dialog", "Grid"))
        self.groupBox_9.setTitle(_translate("Dialog", "Autobackup"))
        self.label_24.setText(_translate("Dialog", "Enable"))
        self.checkBox_autobackupEnable.setToolTip(_translate("Dialog", "Enables autobackup. Highly recommended especially until the program becomes stable. Disable if you are handling large schematics and are seeing noticeable slowdown during interactions."))
        self.label_25.setText(_translate("Dialog", "Timer interval (sec)"))
        self.spinBox_autobackupTimerInterval.setToolTip(_translate("Dialog", "Sets the time interval between autobackups in seconds. Set to a low value if you\'re frequently experiencing crashes and to a high value if you\'re working with large schematics that take a long time to save/backup."))
        self.groupBox_5.setTitle(_translate("Dialog", "Schematic"))
        self.label_8.setText(_translate("Dialog", "Show previews in save/load dialogs"))
        self.checkBox_showSchematicPreview.setToolTip(_translate("Dialog", "Disable this if there are folders with many schematics which might be significantly slowed down in the load/save dialogs"))
        self.label_15.setText(_translate("Dialog", "Default save folder"))
        self.lineEdit_defaultSchematicSaveFolder.setToolTip(_translate("Dialog", "Pick a default folder for saving schematics to"))
        self.lineEdit_defaultSchematicSaveFolder.setText(_translate("Dialog", "./"))
        self.pushButton_defaultSchematicSaveFolder.setToolTip(_translate("Dialog", "Pick a default folder for saving schematics to"))
        self.pushButton_defaultSchematicSaveFolder.setText(_translate("Dialog", "..."))
        self.groupBox_6.setTitle(_translate("Dialog", "Symbol"))
        self.label_16.setText(_translate("Dialog", "Show previews in save/load dialogs"))
        self.checkBox_showSymbolPreview.setToolTip(_translate("Dialog", "Disable this if there are folders with many symbols which might be significantly slowed down in the load/save dialogs"))
        self.label_17.setText(_translate("Dialog", "Default save folder"))
        self.lineEdit_defaultSymbolSaveFolder.setToolTip(_translate("Dialog", "Pick a default folder for saving symbols to"))
        self.lineEdit_defaultSymbolSaveFolder.setText(_translate("Dialog", "Resources/Symbols/Custom"))
        self.pushButton_defaultSymbolSaveFolder.setToolTip(_translate("Dialog", "Pick a default folder for saving symbols to"))
        self.pushButton_defaultSymbolSaveFolder.setText(_translate("Dialog", "..."))
        self.groupBox_7.setTitle(_translate("Dialog", "Export"))
        self.label_18.setText(_translate("Dialog", "Default format"))
        self.comboBox_defaultExportFormat.setToolTip(_translate("Dialog", "Pick a default format for exporting to"))
        self.comboBox_defaultExportFormat.setItemText(0, _translate("Dialog", "PDF"))
        self.comboBox_defaultExportFormat.setItemText(1, _translate("Dialog", "SVG"))
        self.comboBox_defaultExportFormat.setItemText(2, _translate("Dialog", "PNG"))
        self.comboBox_defaultExportFormat.setItemText(3, _translate("Dialog", "JPG"))
        self.comboBox_defaultExportFormat.setItemText(4, _translate("Dialog", "BMP"))
        self.comboBox_defaultExportFormat.setItemText(5, _translate("Dialog", "TIFF"))
        self.label_19.setText(_translate("Dialog", "Default folder"))
        self.lineEdit_defaultExportFolder.setToolTip(_translate("Dialog", "Pick a default folder for exporting to"))
        self.lineEdit_defaultExportFolder.setText(_translate("Dialog", "./"))
        self.pushButton_defaultExportFolder.setToolTip(_translate("Dialog", "Pick a default folder for exporting to"))
        self.pushButton_defaultExportFolder.setText(_translate("Dialog", "..."))
        self.label_20.setText(_translate("Dialog", "Whitespace padding"))
        self.doubleSpinBox_exportImageWhitespacePadding.setToolTip(_translate("Dialog", "Sets the scaling factor of the overall exported image to the tight bounding box of elements within the scene. The difference between the two sizes is effectively the whitespace near the edges of the image."))
        self.label_21.setText(_translate("Dialog", "Scale factor (only for raster formats)"))
        self.doubleSpinBox_exportImageScaleFactor.setToolTip(_translate("Dialog", "Sets the scaling factor of the exported image. You can tune this value to tradeoff speed of export with the resolution of the resultant images."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_saveExport), _translate("Dialog", "Save/Export"))
        self.label_29.setText(_translate("Dialog", "Show diamond at mouse position"))
        self.checkBox_showMouseRect.setToolTip(_translate("Dialog", "Shows a grey diamond at the current mouse position on the grid"))
        self.groupBox_11.setTitle(_translate("Dialog", "Animations"))
        self.label_30.setText(_translate("Dialog", "Show animations while panning"))
        self.checkBox_showAnimationPan.setToolTip(_translate("Dialog", "Toggle transition animations while panning"))
        self.label_31.setText(_translate("Dialog", "Show animations while zooming"))
        self.checkBox_showAnimationZoom.setToolTip(_translate("Dialog", "Toggle transition animations while zooming"))
        self.groupBox_12.setTitle(_translate("Dialog", "Panning/zooming"))
        self.label_32.setText(_translate("Dialog", "On mouse scroll"))
        self.comboBox_scrollModifierNone.setToolTip(_translate("Dialog", "Select behaviour when the mouse wheel is scrolled"))
        self.comboBox_scrollModifierNone.setItemText(0, _translate("Dialog", "Zoom"))
        self.comboBox_scrollModifierNone.setItemText(1, _translate("Dialog", "Pan horizontally"))
        self.comboBox_scrollModifierNone.setItemText(2, _translate("Dialog", "Pan vertically"))
        self.label_33.setText(_translate("Dialog", "On Ctrl+mouse scroll"))
        self.comboBox_scrollModifierCtrl.setToolTip(_translate("Dialog", "Select behaviour when the mouse wheel is scrolled while the Ctrl key is pressed"))
        self.comboBox_scrollModifierCtrl.setItemText(0, _translate("Dialog", "Zoom"))
        self.comboBox_scrollModifierCtrl.setItemText(1, _translate("Dialog", "Pan horizontally"))
        self.comboBox_scrollModifierCtrl.setItemText(2, _translate("Dialog", "Pan vertically"))
        self.label_34.setText(_translate("Dialog", "On Shift+mouse scroll"))
        self.comboBox_scrollModifierShift.setToolTip(_translate("Dialog", "Select behaviour when the mouse wheel is scrolled while the Shift key is pressed"))
        self.comboBox_scrollModifierShift.setItemText(0, _translate("Dialog", "Zoom"))
        self.comboBox_scrollModifierShift.setItemText(1, _translate("Dialog", "Pan horizontally"))
        self.comboBox_scrollModifierShift.setItemText(2, _translate("Dialog", "Pan vertically"))
        self.label_35.setText(_translate("Dialog", "Invert scroll direction for zoom"))
        self.checkBox_zoomInvert.setToolTip(_translate("Dialog", "Invert the zooming behaviour (may be useful when using laptops with trackpads)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_mouse), _translate("Dialog", "Mouse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_shortcuts), _translate("Dialog", "Shortcuts"))
        self.groupBox_13.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.groupBox_13.setTitle(_translate("Dialog", "Quick add symbols"))
        self.label_38.setText(_translate("Dialog", "Symbol 1"))
        self.lineEdit_quickAddSymbol1.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.lineEdit_quickAddSymbol1.setText(_translate("Dialog", "Resources/Symbols/Standard/Resistor.sym"))
        self.pushButton_quickAddSymbol1.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.pushButton_quickAddSymbol1.setText(_translate("Dialog", "..."))
        self.label_39.setText(_translate("Dialog", "Symbol 2"))
        self.lineEdit_quickAddSymbol2.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.lineEdit_quickAddSymbol2.setText(_translate("Dialog", "Resources/Symbols/Standard/Resistor.sym"))
        self.pushButton_quickAddSymbol2.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.pushButton_quickAddSymbol2.setText(_translate("Dialog", "..."))
        self.label_40.setText(_translate("Dialog", "Symbol 3"))
        self.lineEdit_quickAddSymbol3.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.lineEdit_quickAddSymbol3.setText(_translate("Dialog", "Resources/Symbols/Standard/Resistor.sym"))
        self.pushButton_quickAddSymbol3.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.pushButton_quickAddSymbol3.setText(_translate("Dialog", "..."))
        self.label_41.setText(_translate("Dialog", "Symbol 4"))
        self.lineEdit_quickAddSymbol4.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.lineEdit_quickAddSymbol4.setText(_translate("Dialog", "Resources/Symbols/Standard/Resistor.sym"))
        self.pushButton_quickAddSymbol4.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.pushButton_quickAddSymbol4.setText(_translate("Dialog", "..."))
        self.label_42.setText(_translate("Dialog", "Symbol 5"))
        self.lineEdit_quickAddSymbol5.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.lineEdit_quickAddSymbol5.setText(_translate("Dialog", "Resources/Symbols/Standard/Resistor.sym"))
        self.pushButton_quickAddSymbol5.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.pushButton_quickAddSymbol5.setText(_translate("Dialog", "..."))
        self.groupBox_14.setTitle(_translate("Dialog", "Symbol viewer folders"))
        self.label_28.setText(_translate("Dialog", "Default folder"))
        self.lineEdit_defaultSymbolPreviewFolder.setToolTip(_translate("Dialog", "Pick a default folder for saving schematics to"))
        self.lineEdit_defaultSymbolPreviewFolder.setText(_translate("Dialog", "Resources/Symbols/Standard"))
        self.pushButton_defaultSymbolPreviewFolder.setToolTip(_translate("Dialog", "Pick a default folder for saving schematics to"))
        self.pushButton_defaultSymbolPreviewFolder.setText(_translate("Dialog", "..."))
        self.label_43.setText(_translate("Dialog", "Folder 1"))
        self.lineEdit_symbolPreviewFolder1.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.lineEdit_symbolPreviewFolder1.setText(_translate("Dialog", "Resources/Symbols/Standard"))
        self.pushButton_symbolPreviewFolder1.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.pushButton_symbolPreviewFolder1.setText(_translate("Dialog", "..."))
        self.label_45.setText(_translate("Dialog", "Folder 2"))
        self.lineEdit_symbolPreviewFolder2.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.lineEdit_symbolPreviewFolder2.setText(_translate("Dialog", "Resources/Symbols/Standard"))
        self.pushButton_symbolPreviewFolder2.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.pushButton_symbolPreviewFolder2.setText(_translate("Dialog", "..."))
        self.label_46.setText(_translate("Dialog", "Folder 3"))
        self.lineEdit_symbolPreviewFolder3.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.lineEdit_symbolPreviewFolder3.setText(_translate("Dialog", "Resources/Symbols/Standard"))
        self.pushButton_symbolPreviewFolder3.setToolTip(_translate("Dialog", "Pick a symbol for adding via customisable shortcut"))
        self.pushButton_symbolPreviewFolder3.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_misc), _translate("Dialog", "Misc."))
        self.label_4.setText(_translate("Dialog", "Note: These values are defaults that will be used when the program restarts. To change these values for just the current session, please use the Edit menu."))

