# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/gui/ycircuit_optionsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(800, 600))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_printing = QtWidgets.QWidget()
        self.tab_printing.setObjectName("tab_printing")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_printing)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_printing)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.comboBox_penWidth = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_penWidth.setObjectName("comboBox_penWidth")
        self.comboBox_penWidth.addItem("")
        self.comboBox_penWidth.addItem("")
        self.comboBox_penWidth.addItem("")
        self.comboBox_penWidth.addItem("")
        self.comboBox_penWidth.addItem("")
        self.gridLayout.addWidget(self.comboBox_penWidth, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_penStyle = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_penStyle.setObjectName("comboBox_penStyle")
        self.comboBox_penStyle.addItem("")
        self.comboBox_penStyle.addItem("")
        self.comboBox_penStyle.addItem("")
        self.comboBox_penStyle.addItem("")
        self.comboBox_penStyle.addItem("")
        self.gridLayout.addWidget(self.comboBox_penStyle, 2, 2, 1, 1)
        self.comboBox_penColour = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_penColour.setObjectName("comboBox_penColour")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.comboBox_penColour.addItem("")
        self.gridLayout.addWidget(self.comboBox_penColour, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_printing)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        self.comboBox_brushColour = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_brushColour.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_brushColour.setObjectName("comboBox_brushColour")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.comboBox_brushColour.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_brushColour, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 1, 1, 1)
        self.comboBox_brushStyle = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_brushStyle.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox_brushStyle.setObjectName("comboBox_brushStyle")
        self.comboBox_brushStyle.addItem("")
        self.comboBox_brushStyle.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_brushStyle, 1, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_printing, "")
        self.tab_grid = QtWidgets.QWidget()
        self.tab_grid.setObjectName("tab_grid")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_grid)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.tab_grid)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 5, 0, 1, 1)
        self.checkBox_gridShowMinorGridPoints = QtWidgets.QCheckBox(self.tab_grid)
        self.checkBox_gridShowMinorGridPoints.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_gridShowMinorGridPoints.setText("")
        self.checkBox_gridShowMinorGridPoints.setObjectName("checkBox_gridShowMinorGridPoints")
        self.gridLayout_4.addWidget(self.checkBox_gridShowMinorGridPoints, 5, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 4, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 3, 1, 1, 1)
        self.checkBox_gridShowMajorGridPoints = QtWidgets.QCheckBox(self.tab_grid)
        self.checkBox_gridShowMajorGridPoints.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_gridShowMajorGridPoints.setText("")
        self.checkBox_gridShowMajorGridPoints.setObjectName("checkBox_gridShowMajorGridPoints")
        self.gridLayout_4.addWidget(self.checkBox_gridShowMajorGridPoints, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_grid)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 4, 0, 1, 1)
        self.comboBox_gridMajorGridPointSpacing = QtWidgets.QComboBox(self.tab_grid)
        self.comboBox_gridMajorGridPointSpacing.setObjectName("comboBox_gridMajorGridPointSpacing")
        self.comboBox_gridMajorGridPointSpacing.addItem("")
        self.comboBox_gridMajorGridPointSpacing.addItem("")
        self.comboBox_gridMajorGridPointSpacing.addItem("")
        self.comboBox_gridMajorGridPointSpacing.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_gridMajorGridPointSpacing, 4, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_grid)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_grid)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_grid)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 1, 1, 1)
        self.checkBox_gridVisibility = QtWidgets.QCheckBox(self.tab_grid)
        self.checkBox_gridVisibility.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_gridVisibility.setText("")
        self.checkBox_gridVisibility.setObjectName("checkBox_gridVisibility")
        self.gridLayout_4.addWidget(self.checkBox_gridVisibility, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_grid)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 1, 1, 1, 1)
        self.checkBox_gridSnapToGrid = QtWidgets.QCheckBox(self.tab_grid)
        self.checkBox_gridSnapToGrid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_gridSnapToGrid.setText("")
        self.checkBox_gridSnapToGrid.setObjectName("checkBox_gridSnapToGrid")
        self.gridLayout_4.addWidget(self.checkBox_gridSnapToGrid, 1, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 6, 1, 1, 1)
        self.comboBox_gridMinorGridPointSpacing = QtWidgets.QComboBox(self.tab_grid)
        self.comboBox_gridMinorGridPointSpacing.setObjectName("comboBox_gridMinorGridPointSpacing")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.comboBox_gridMinorGridPointSpacing.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_gridMinorGridPointSpacing, 6, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 5, 1, 1, 1)
        self.comboBox_gridSnapToGridSpacing = QtWidgets.QComboBox(self.tab_grid)
        self.comboBox_gridSnapToGridSpacing.setObjectName("comboBox_gridSnapToGridSpacing")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.comboBox_gridSnapToGridSpacing.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_gridSnapToGridSpacing, 2, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_grid)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem13 = QtWidgets.QSpacerItem(20, 184, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.tabWidget.addTab(self.tab_grid, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label_4 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem14 = QtWidgets.QSpacerItem(20, 307, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem15)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_3.addWidget(self.buttonBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_penWidth.setCurrentIndex(1)
        self.comboBox_penStyle.setCurrentIndex(0)
        self.comboBox_penColour.setCurrentIndex(0)
        self.comboBox_brushColour.setCurrentIndex(0)
        self.comboBox_brushStyle.setCurrentIndex(0)
        self.comboBox_gridMinorGridPointSpacing.setCurrentIndex(4)
        self.comboBox_gridSnapToGridSpacing.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.groupBox.setTitle(_translate("Dialog", "Pen"))
        self.label_2.setText(_translate("Dialog", "Default colour"))
        self.comboBox_penWidth.setItemText(0, _translate("Dialog", "2"))
        self.comboBox_penWidth.setItemText(1, _translate("Dialog", "4"))
        self.comboBox_penWidth.setItemText(2, _translate("Dialog", "6"))
        self.comboBox_penWidth.setItemText(3, _translate("Dialog", "8"))
        self.comboBox_penWidth.setItemText(4, _translate("Dialog", "10"))
        self.label_3.setText(_translate("Dialog", "Default style"))
        self.comboBox_penStyle.setItemText(0, _translate("Dialog", "Solid"))
        self.comboBox_penStyle.setItemText(1, _translate("Dialog", "Dash"))
        self.comboBox_penStyle.setItemText(2, _translate("Dialog", "Dot"))
        self.comboBox_penStyle.setItemText(3, _translate("Dialog", "Dash-dot"))
        self.comboBox_penStyle.setItemText(4, _translate("Dialog", "Dash-dot-dot"))
        self.comboBox_penColour.setItemText(0, _translate("Dialog", "Black"))
        self.comboBox_penColour.setItemText(1, _translate("Dialog", "Red"))
        self.comboBox_penColour.setItemText(2, _translate("Dialog", "Blue"))
        self.comboBox_penColour.setItemText(3, _translate("Dialog", "Green"))
        self.comboBox_penColour.setItemText(4, _translate("Dialog", "Cyan"))
        self.comboBox_penColour.setItemText(5, _translate("Dialog", "Magenta"))
        self.comboBox_penColour.setItemText(6, _translate("Dialog", "Yellow"))
        self.label.setText(_translate("Dialog", "Default width"))
        self.groupBox_2.setTitle(_translate("Dialog", "Brush"))
        self.label_9.setText(_translate("Dialog", "Default colour"))
        self.comboBox_brushColour.setItemText(0, _translate("Dialog", "Black"))
        self.comboBox_brushColour.setItemText(1, _translate("Dialog", "Red"))
        self.comboBox_brushColour.setItemText(2, _translate("Dialog", "Blue"))
        self.comboBox_brushColour.setItemText(3, _translate("Dialog", "Green"))
        self.comboBox_brushColour.setItemText(4, _translate("Dialog", "Cyan"))
        self.comboBox_brushColour.setItemText(5, _translate("Dialog", "Magenta"))
        self.comboBox_brushColour.setItemText(6, _translate("Dialog", "Yellow"))
        self.label_10.setText(_translate("Dialog", "Default style"))
        self.comboBox_brushStyle.setItemText(0, _translate("Dialog", "No fill"))
        self.comboBox_brushStyle.setItemText(1, _translate("Dialog", "Solid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_printing), _translate("Dialog", "Painting"))
        self.label_6.setText(_translate("Dialog", "Show minor grid points"))
        self.label_13.setText(_translate("Dialog", "Major grid point spacing"))
        self.comboBox_gridMajorGridPointSpacing.setItemText(0, _translate("Dialog", "100"))
        self.comboBox_gridMajorGridPointSpacing.setItemText(1, _translate("Dialog", "200"))
        self.comboBox_gridMajorGridPointSpacing.setItemText(2, _translate("Dialog", "300"))
        self.comboBox_gridMajorGridPointSpacing.setItemText(3, _translate("Dialog", "400"))
        self.label_12.setText(_translate("Dialog", "Show major grid points"))
        self.label_5.setText(_translate("Dialog", "Minor grid point spacing"))
        self.label_11.setText(_translate("Dialog", "Visibility"))
        self.label_14.setText(_translate("Dialog", "Snap to grid"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(2, _translate("Dialog", "5"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(3, _translate("Dialog", "10"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(4, _translate("Dialog", "20"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(5, _translate("Dialog", "30"))
        self.comboBox_gridMinorGridPointSpacing.setItemText(6, _translate("Dialog", "40"))
        self.comboBox_gridSnapToGridSpacing.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_gridSnapToGridSpacing.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_gridSnapToGridSpacing.setItemText(2, _translate("Dialog", "5"))
        self.comboBox_gridSnapToGridSpacing.setItemText(3, _translate("Dialog", "10"))
        self.comboBox_gridSnapToGridSpacing.setItemText(4, _translate("Dialog", "20"))
        self.comboBox_gridSnapToGridSpacing.setItemText(5, _translate("Dialog", "30"))
        self.comboBox_gridSnapToGridSpacing.setItemText(6, _translate("Dialog", "40"))
        self.label_7.setText(_translate("Dialog", "Snap to grid spacing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_grid), _translate("Dialog", "Grid"))
        self.label_4.setText(_translate("Dialog", "Note: These values are defaults that will be used when the program restarts. To change these values for just the current session, please use the Edit menu."))

