image: python:3.5.2

pipelines:
  branches:
    develop:
      - step:
          caches:
            - pip
          script: # Modify the commands below to build your repository.
            - pip install --upgrade pip
            - pip install sip
            - pip install PyQt5
            - pip install PyInstaller
            - pip install sympy
            - pyinstaller -y top.spec
            - tar -cvzf dist/ycircuit-develop.tar dist/YCircuit/*
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"dist/ycircuit-develop.tar"