# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'schematic_mainWindow.ui'
#
# Created: Mon Aug  1 18:13:57 2016
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1089, 790)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.drawingArea = DrawingArea(self.centralwidget)
        self.drawingArea.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.TextAntialiasing)
        self.drawingArea.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.drawingArea.setCacheMode(QtGui.QGraphicsView.CacheBackground)
        self.drawingArea.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.drawingArea.setResizeAnchor(QtGui.QGraphicsView.AnchorUnderMouse)
        self.drawingArea.setViewportUpdateMode(QtGui.QGraphicsView.FullViewportUpdate)
        self.drawingArea.setRubberBandSelectionMode(QtCore.Qt.ContainsItemShape)
        self.drawingArea.setObjectName(_fromUtf8("drawingArea"))
        self.horizontalLayout.addWidget(self.drawingArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_setPenWidth = QtGui.QMenu(self.menu_Edit)
        self.menu_setPenWidth.setObjectName(_fromUtf8("menu_setPenWidth"))
        self.menu_setPenColour = QtGui.QMenu(self.menu_Edit)
        self.menu_setPenColour.setObjectName(_fromUtf8("menu_setPenColour"))
        self.menu_setPenStyle = QtGui.QMenu(self.menu_Edit)
        self.menu_setPenStyle.setObjectName(_fromUtf8("menu_setPenStyle"))
        self.menu_setFillColour = QtGui.QMenu(self.menu_Edit)
        self.menu_setFillColour.setObjectName(_fromUtf8("menu_setFillColour"))
        self.menu_setFillStyle = QtGui.QMenu(self.menu_Edit)
        self.menu_setFillStyle.setObjectName(_fromUtf8("menu_setFillStyle"))
        self.menu_AddSymbol = QtGui.QMenu(self.menubar)
        self.menu_AddSymbol.setObjectName(_fromUtf8("menu_AddSymbol"))
        self.menu_Transistor = QtGui.QMenu(self.menu_AddSymbol)
        self.menu_Transistor.setObjectName(_fromUtf8("menu_Transistor"))
        self.menu_N_type_MOSFET = QtGui.QMenu(self.menu_Transistor)
        self.menu_N_type_MOSFET.setObjectName(_fromUtf8("menu_N_type_MOSFET"))
        self.menu_P_type_MOSFET = QtGui.QMenu(self.menu_Transistor)
        self.menu_P_type_MOSFET.setObjectName(_fromUtf8("menu_P_type_MOSFET"))
        self.menuSources = QtGui.QMenu(self.menu_AddSymbol)
        self.menuSources.setObjectName(_fromUtf8("menuSources"))
        self.menu_DC = QtGui.QMenu(self.menuSources)
        self.menu_DC.setObjectName(_fromUtf8("menu_DC"))
        self.menu_AC = QtGui.QMenu(self.menuSources)
        self.menu_AC.setObjectName(_fromUtf8("menu_AC"))
        self.menu_Controlled = QtGui.QMenu(self.menuSources)
        self.menu_Controlled.setObjectName(_fromUtf8("menu_Controlled"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        self.menuSh_ape = QtGui.QMenu(self.menubar)
        self.menuSh_ape.setObjectName(_fromUtf8("menuSh_ape"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_exportFile = QtGui.QAction(MainWindow)
        self.action_exportFile.setObjectName(_fromUtf8("action_exportFile"))
        self.action_quit = QtGui.QAction(MainWindow)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_move = QtGui.QAction(MainWindow)
        self.action_move.setObjectName(_fromUtf8("action_move"))
        self.action_copy = QtGui.QAction(MainWindow)
        self.action_copy.setObjectName(_fromUtf8("action_copy"))
        self.action_addWire = QtGui.QAction(MainWindow)
        self.action_addWire.setObjectName(_fromUtf8("action_addWire"))
        self.action_addResistor = QtGui.QAction(MainWindow)
        self.action_addResistor.setObjectName(_fromUtf8("action_addResistor"))
        self.action_addDot = QtGui.QAction(MainWindow)
        self.action_addDot.setObjectName(_fromUtf8("action_addDot"))
        self.action_setWidth2 = QtGui.QAction(MainWindow)
        self.action_setWidth2.setCheckable(True)
        self.action_setWidth2.setChecked(False)
        self.action_setWidth2.setObjectName(_fromUtf8("action_setWidth2"))
        self.action_setWidth4 = QtGui.QAction(MainWindow)
        self.action_setWidth4.setCheckable(True)
        self.action_setWidth4.setChecked(True)
        self.action_setWidth4.setObjectName(_fromUtf8("action_setWidth4"))
        self.action_setWidth6 = QtGui.QAction(MainWindow)
        self.action_setWidth6.setCheckable(True)
        self.action_setWidth6.setObjectName(_fromUtf8("action_setWidth6"))
        self.action_setWidth8 = QtGui.QAction(MainWindow)
        self.action_setWidth8.setCheckable(True)
        self.action_setWidth8.setObjectName(_fromUtf8("action_setWidth8"))
        self.action_setWidth10 = QtGui.QAction(MainWindow)
        self.action_setWidth10.setCheckable(True)
        self.action_setWidth10.setObjectName(_fromUtf8("action_setWidth10"))
        self.action_rotate = QtGui.QAction(MainWindow)
        self.action_rotate.setObjectName(_fromUtf8("action_rotate"))
        self.action_mirror = QtGui.QAction(MainWindow)
        self.action_mirror.setObjectName(_fromUtf8("action_mirror"))
        self.action_fitToView = QtGui.QAction(MainWindow)
        self.action_fitToView.setObjectName(_fromUtf8("action_fitToView"))
        self.action_showGrid = QtGui.QAction(MainWindow)
        self.action_showGrid.setCheckable(True)
        self.action_showGrid.setChecked(True)
        self.action_showGrid.setObjectName(_fromUtf8("action_showGrid"))
        self.action_delete = QtGui.QAction(MainWindow)
        self.action_delete.setObjectName(_fromUtf8("action_delete"))
        self.action_setPenColourRed = QtGui.QAction(MainWindow)
        self.action_setPenColourRed.setCheckable(True)
        self.action_setPenColourRed.setObjectName(_fromUtf8("action_setPenColourRed"))
        self.action_setPenColourBlue = QtGui.QAction(MainWindow)
        self.action_setPenColourBlue.setCheckable(True)
        self.action_setPenColourBlue.setObjectName(_fromUtf8("action_setPenColourBlue"))
        self.action_setPenColourGreen = QtGui.QAction(MainWindow)
        self.action_setPenColourGreen.setCheckable(True)
        self.action_setPenColourGreen.setObjectName(_fromUtf8("action_setPenColourGreen"))
        self.action_setPenColourBlack = QtGui.QAction(MainWindow)
        self.action_setPenColourBlack.setCheckable(True)
        self.action_setPenColourBlack.setChecked(True)
        self.action_setPenColourBlack.setObjectName(_fromUtf8("action_setPenColourBlack"))
        self.action_setPenStyleSolid = QtGui.QAction(MainWindow)
        self.action_setPenStyleSolid.setCheckable(True)
        self.action_setPenStyleSolid.setChecked(True)
        self.action_setPenStyleSolid.setObjectName(_fromUtf8("action_setPenStyleSolid"))
        self.action_setPenStyleDash = QtGui.QAction(MainWindow)
        self.action_setPenStyleDash.setCheckable(True)
        self.action_setPenStyleDash.setObjectName(_fromUtf8("action_setPenStyleDash"))
        self.action_setPenStyleDot = QtGui.QAction(MainWindow)
        self.action_setPenStyleDot.setCheckable(True)
        self.action_setPenStyleDot.setObjectName(_fromUtf8("action_setPenStyleDot"))
        self.action_setPenStyleDashDot = QtGui.QAction(MainWindow)
        self.action_setPenStyleDashDot.setCheckable(True)
        self.action_setPenStyleDashDot.setObjectName(_fromUtf8("action_setPenStyleDashDot"))
        self.action_setPenStyleDashDotDot = QtGui.QAction(MainWindow)
        self.action_setPenStyleDashDotDot.setCheckable(True)
        self.action_setPenStyleDashDotDot.setObjectName(_fromUtf8("action_setPenStyleDashDotDot"))
        self.action_addCapacitor = QtGui.QAction(MainWindow)
        self.action_addCapacitor.setObjectName(_fromUtf8("action_addCapacitor"))
        self.action_addGround = QtGui.QAction(MainWindow)
        self.action_addGround.setObjectName(_fromUtf8("action_addGround"))
        self.action_setBrushColourBlack = QtGui.QAction(MainWindow)
        self.action_setBrushColourBlack.setCheckable(True)
        self.action_setBrushColourBlack.setChecked(True)
        self.action_setBrushColourBlack.setObjectName(_fromUtf8("action_setBrushColourBlack"))
        self.action_setBrushColourRed = QtGui.QAction(MainWindow)
        self.action_setBrushColourRed.setCheckable(True)
        self.action_setBrushColourRed.setObjectName(_fromUtf8("action_setBrushColourRed"))
        self.action_setBrushColourBlue = QtGui.QAction(MainWindow)
        self.action_setBrushColourBlue.setCheckable(True)
        self.action_setBrushColourBlue.setObjectName(_fromUtf8("action_setBrushColourBlue"))
        self.action_setBrushColourGreen = QtGui.QAction(MainWindow)
        self.action_setBrushColourGreen.setObjectName(_fromUtf8("action_setBrushColourGreen"))
        self.action_setBrushStyleNone = QtGui.QAction(MainWindow)
        self.action_setBrushStyleNone.setCheckable(True)
        self.action_setBrushStyleNone.setChecked(True)
        self.action_setBrushStyleNone.setObjectName(_fromUtf8("action_setBrushStyleNone"))
        self.action_setBrushStyleSolid = QtGui.QAction(MainWindow)
        self.action_setBrushStyleSolid.setCheckable(True)
        self.action_setBrushStyleSolid.setObjectName(_fromUtf8("action_setBrushStyleSolid"))
        self.action_addNPNBJT = QtGui.QAction(MainWindow)
        self.action_addNPNBJT.setObjectName(_fromUtf8("action_addNPNBJT"))
        self.action_addPNPBJT = QtGui.QAction(MainWindow)
        self.action_addPNPBJT.setObjectName(_fromUtf8("action_addPNPBJT"))
        self.action_addNMOSWithArrow = QtGui.QAction(MainWindow)
        self.action_addNMOSWithArrow.setObjectName(_fromUtf8("action_addNMOSWithArrow"))
        self.action_addNMOSWithoutArrow = QtGui.QAction(MainWindow)
        self.action_addNMOSWithoutArrow.setObjectName(_fromUtf8("action_addNMOSWithoutArrow"))
        self.action_addPMOSWithArrow = QtGui.QAction(MainWindow)
        self.action_addPMOSWithArrow.setObjectName(_fromUtf8("action_addPMOSWithArrow"))
        self.action_addPMOSWithoutArrow = QtGui.QAction(MainWindow)
        self.action_addPMOSWithoutArrow.setObjectName(_fromUtf8("action_addPMOSWithoutArrow"))
        self.action_saveSymbol = QtGui.QAction(MainWindow)
        self.action_saveSymbol.setObjectName(_fromUtf8("action_saveSymbol"))
        self.action_loadSymbol = QtGui.QAction(MainWindow)
        self.action_loadSymbol.setObjectName(_fromUtf8("action_loadSymbol"))
        self.action_saveSchematic = QtGui.QAction(MainWindow)
        self.action_saveSchematic.setObjectName(_fromUtf8("action_saveSchematic"))
        self.action_loadSchematic = QtGui.QAction(MainWindow)
        self.action_loadSchematic.setObjectName(_fromUtf8("action_loadSchematic"))
        self.action_addLine = QtGui.QAction(MainWindow)
        self.action_addLine.setObjectName(_fromUtf8("action_addLine"))
        self.action_addRectangle = QtGui.QAction(MainWindow)
        self.action_addRectangle.setObjectName(_fromUtf8("action_addRectangle"))
        self.action_addCircle = QtGui.QAction(MainWindow)
        self.action_addCircle.setObjectName(_fromUtf8("action_addCircle"))
        self.action_addEllipse = QtGui.QAction(MainWindow)
        self.action_addEllipse.setObjectName(_fromUtf8("action_addEllipse"))
        self.action_snapToGrid = QtGui.QAction(MainWindow)
        self.action_snapToGrid.setCheckable(True)
        self.action_snapToGrid.setChecked(True)
        self.action_snapToGrid.setObjectName(_fromUtf8("action_snapToGrid"))
        self.action_addTextBox = QtGui.QAction(MainWindow)
        self.action_addTextBox.setObjectName(_fromUtf8("action_addTextBox"))
        self.action_setPenColourCyan = QtGui.QAction(MainWindow)
        self.action_setPenColourCyan.setObjectName(_fromUtf8("action_setPenColourCyan"))
        self.action_setPenColourMagenta = QtGui.QAction(MainWindow)
        self.action_setPenColourMagenta.setObjectName(_fromUtf8("action_setPenColourMagenta"))
        self.action_setPenColourYellow = QtGui.QAction(MainWindow)
        self.action_setPenColourYellow.setObjectName(_fromUtf8("action_setPenColourYellow"))
        self.action_setBrushColourCyan = QtGui.QAction(MainWindow)
        self.action_setBrushColourCyan.setObjectName(_fromUtf8("action_setBrushColourCyan"))
        self.action_setBrushColourMagenta = QtGui.QAction(MainWindow)
        self.action_setBrushColourMagenta.setObjectName(_fromUtf8("action_setBrushColourMagenta"))
        self.action_setBrushColourYellow = QtGui.QAction(MainWindow)
        self.action_setBrushColourYellow.setObjectName(_fromUtf8("action_setBrushColourYellow"))
        self.action_addDCVoltageSource = QtGui.QAction(MainWindow)
        self.action_addDCVoltageSource.setObjectName(_fromUtf8("action_addDCVoltageSource"))
        self.action_addDCCurrentSource = QtGui.QAction(MainWindow)
        self.action_addDCCurrentSource.setObjectName(_fromUtf8("action_addDCCurrentSource"))
        self.action_addACVoltageSource = QtGui.QAction(MainWindow)
        self.action_addACVoltageSource.setObjectName(_fromUtf8("action_addACVoltageSource"))
        self.action_addACCurrentSource = QtGui.QAction(MainWindow)
        self.action_addACCurrentSource.setObjectName(_fromUtf8("action_addACCurrentSource"))
        self.action_addVCVS = QtGui.QAction(MainWindow)
        self.action_addVCVS.setObjectName(_fromUtf8("action_addVCVS"))
        self.action_addVCCS = QtGui.QAction(MainWindow)
        self.action_addVCCS.setObjectName(_fromUtf8("action_addVCCS"))
        self.action_addCCVS = QtGui.QAction(MainWindow)
        self.action_addCCVS.setObjectName(_fromUtf8("action_addCCVS"))
        self.action_addCCCS = QtGui.QAction(MainWindow)
        self.action_addCCCS.setObjectName(_fromUtf8("action_addCCCS"))
        self.action_addArc = QtGui.QAction(MainWindow)
        self.action_addArc.setObjectName(_fromUtf8("action_addArc"))
        self.menu_File.addAction(self.action_saveSchematic)
        self.menu_File.addAction(self.action_loadSchematic)
        self.menu_File.addAction(self.action_saveSymbol)
        self.menu_File.addAction(self.action_loadSymbol)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_exportFile)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_quit)
        self.menu_setPenWidth.addAction(self.action_setWidth2)
        self.menu_setPenWidth.addAction(self.action_setWidth4)
        self.menu_setPenWidth.addAction(self.action_setWidth6)
        self.menu_setPenWidth.addAction(self.action_setWidth8)
        self.menu_setPenWidth.addAction(self.action_setWidth10)
        self.menu_setPenColour.addAction(self.action_setPenColourBlack)
        self.menu_setPenColour.addAction(self.action_setPenColourRed)
        self.menu_setPenColour.addAction(self.action_setPenColourBlue)
        self.menu_setPenColour.addAction(self.action_setPenColourGreen)
        self.menu_setPenColour.addAction(self.action_setPenColourCyan)
        self.menu_setPenColour.addAction(self.action_setPenColourMagenta)
        self.menu_setPenColour.addAction(self.action_setPenColourYellow)
        self.menu_setPenStyle.addAction(self.action_setPenStyleSolid)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDash)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDot)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDashDot)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDashDotDot)
        self.menu_setFillColour.addAction(self.action_setBrushColourBlack)
        self.menu_setFillColour.addAction(self.action_setBrushColourRed)
        self.menu_setFillColour.addAction(self.action_setBrushColourBlue)
        self.menu_setFillColour.addAction(self.action_setBrushColourGreen)
        self.menu_setFillColour.addAction(self.action_setBrushColourCyan)
        self.menu_setFillColour.addAction(self.action_setBrushColourMagenta)
        self.menu_setFillColour.addAction(self.action_setBrushColourYellow)
        self.menu_setFillStyle.addAction(self.action_setBrushStyleNone)
        self.menu_setFillStyle.addAction(self.action_setBrushStyleSolid)
        self.menu_Edit.addAction(self.action_delete)
        self.menu_Edit.addAction(self.action_move)
        self.menu_Edit.addAction(self.action_copy)
        self.menu_Edit.addAction(self.action_rotate)
        self.menu_Edit.addAction(self.action_mirror)
        self.menu_Edit.addAction(self.menu_setPenWidth.menuAction())
        self.menu_Edit.addAction(self.menu_setPenColour.menuAction())
        self.menu_Edit.addAction(self.menu_setPenStyle.menuAction())
        self.menu_Edit.addAction(self.menu_setFillColour.menuAction())
        self.menu_Edit.addAction(self.menu_setFillStyle.menuAction())
        self.menu_N_type_MOSFET.addAction(self.action_addNMOSWithArrow)
        self.menu_N_type_MOSFET.addAction(self.action_addNMOSWithoutArrow)
        self.menu_P_type_MOSFET.addAction(self.action_addPMOSWithArrow)
        self.menu_P_type_MOSFET.addAction(self.action_addPMOSWithoutArrow)
        self.menu_Transistor.addAction(self.menu_N_type_MOSFET.menuAction())
        self.menu_Transistor.addAction(self.menu_P_type_MOSFET.menuAction())
        self.menu_Transistor.addAction(self.action_addNPNBJT)
        self.menu_Transistor.addAction(self.action_addPNPBJT)
        self.menu_DC.addAction(self.action_addDCVoltageSource)
        self.menu_DC.addAction(self.action_addDCCurrentSource)
        self.menu_AC.addAction(self.action_addACVoltageSource)
        self.menu_AC.addAction(self.action_addACCurrentSource)
        self.menu_Controlled.addAction(self.action_addVCVS)
        self.menu_Controlled.addAction(self.action_addVCCS)
        self.menu_Controlled.addAction(self.action_addCCVS)
        self.menu_Controlled.addAction(self.action_addCCCS)
        self.menuSources.addAction(self.menu_DC.menuAction())
        self.menuSources.addAction(self.menu_AC.menuAction())
        self.menuSources.addAction(self.menu_Controlled.menuAction())
        self.menu_AddSymbol.addAction(self.action_addWire)
        self.menu_AddSymbol.addAction(self.action_addResistor)
        self.menu_AddSymbol.addAction(self.action_addCapacitor)
        self.menu_AddSymbol.addAction(self.action_addGround)
        self.menu_AddSymbol.addAction(self.action_addDot)
        self.menu_AddSymbol.addAction(self.menu_Transistor.menuAction())
        self.menu_AddSymbol.addAction(self.menuSources.menuAction())
        self.menu_View.addAction(self.action_fitToView)
        self.menu_View.addAction(self.action_showGrid)
        self.menu_View.addAction(self.action_snapToGrid)
        self.menuSh_ape.addAction(self.action_addLine)
        self.menuSh_ape.addAction(self.action_addArc)
        self.menuSh_ape.addAction(self.action_addRectangle)
        self.menuSh_ape.addAction(self.action_addCircle)
        self.menuSh_ape.addAction(self.action_addEllipse)
        self.menuSh_ape.addAction(self.action_addTextBox)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menuSh_ape.menuAction())
        self.menubar.addAction(self.menu_AddSymbol.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Schematic draw", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Edit.setTitle(QtGui.QApplication.translate("MainWindow", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_setPenWidth.setTitle(QtGui.QApplication.translate("MainWindow", "&Width", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_setPenColour.setTitle(QtGui.QApplication.translate("MainWindow", "&Colour", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_setPenStyle.setTitle(QtGui.QApplication.translate("MainWindow", "&Pen style", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_setFillColour.setTitle(QtGui.QApplication.translate("MainWindow", "Fill colour", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_setFillStyle.setTitle(QtGui.QApplication.translate("MainWindow", "Fill style", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_AddSymbol.setTitle(QtGui.QApplication.translate("MainWindow", "&Symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Transistor.setTitle(QtGui.QApplication.translate("MainWindow", "&Transistor", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_N_type_MOSFET.setTitle(QtGui.QApplication.translate("MainWindow", "&N-type MOSFET", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_P_type_MOSFET.setTitle(QtGui.QApplication.translate("MainWindow", "&P-type MOSFET", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSources.setTitle(QtGui.QApplication.translate("MainWindow", "&Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_DC.setTitle(QtGui.QApplication.translate("MainWindow", "&DC", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_AC.setTitle(QtGui.QApplication.translate("MainWindow", "&AC", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Controlled.setTitle(QtGui.QApplication.translate("MainWindow", "&Controlled", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_View.setTitle(QtGui.QApplication.translate("MainWindow", "&View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSh_ape.setTitle(QtGui.QApplication.translate("MainWindow", "Sh&ape", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exportFile.setText(QtGui.QApplication.translate("MainWindow", "Export file", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exportFile.setToolTip(QtGui.QApplication.translate("MainWindow", "Exports file as an image", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exportFile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setToolTip(QtGui.QApplication.translate("MainWindow", "Quits the program", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_move.setText(QtGui.QApplication.translate("MainWindow", "Move", None, QtGui.QApplication.UnicodeUTF8))
        self.action_move.setToolTip(QtGui.QApplication.translate("MainWindow", "Move selected items", None, QtGui.QApplication.UnicodeUTF8))
        self.action_move.setShortcut(QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.action_copy.setText(QtGui.QApplication.translate("MainWindow", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.action_copy.setToolTip(QtGui.QApplication.translate("MainWindow", "Copy selected items", None, QtGui.QApplication.UnicodeUTF8))
        self.action_copy.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addWire.setText(QtGui.QApplication.translate("MainWindow", "&Wire", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addWire.setToolTip(QtGui.QApplication.translate("MainWindow", "Draws a wire", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addResistor.setText(QtGui.QApplication.translate("MainWindow", "&Resistor", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addResistor.setToolTip(QtGui.QApplication.translate("MainWindow", "Draws a resistor", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addDot.setText(QtGui.QApplication.translate("MainWindow", "Connection &dot", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addDot.setToolTip(QtGui.QApplication.translate("MainWindow", "Draws a dot signifying connectivity", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth2.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the width of currently selected items to 2", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth4.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the width of currently selected items to 4", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth6.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the width of currently selected items to 6", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth8.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the width of currently selected items to 8", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth10.setText(QtGui.QApplication.translate("MainWindow", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setWidth10.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the width of currently selected items to 10", None, QtGui.QApplication.UnicodeUTF8))
        self.action_rotate.setText(QtGui.QApplication.translate("MainWindow", "Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.action_rotate.setToolTip(QtGui.QApplication.translate("MainWindow", "Rotate selected items", None, QtGui.QApplication.UnicodeUTF8))
        self.action_rotate.setShortcut(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.action_mirror.setText(QtGui.QApplication.translate("MainWindow", "Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.action_mirror.setToolTip(QtGui.QApplication.translate("MainWindow", "Mirror selected items", None, QtGui.QApplication.UnicodeUTF8))
        self.action_mirror.setShortcut(QtGui.QApplication.translate("MainWindow", "Shift+R", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fitToView.setText(QtGui.QApplication.translate("MainWindow", "Fit to view", None, QtGui.QApplication.UnicodeUTF8))
        self.action_fitToView.setShortcut(QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showGrid.setText(QtGui.QApplication.translate("MainWindow", "Show grid", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showGrid.setToolTip(QtGui.QApplication.translate("MainWindow", "Toggle grid visibility", None, QtGui.QApplication.UnicodeUTF8))
        self.action_showGrid.setShortcut(QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.action_delete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.action_delete.setToolTip(QtGui.QApplication.translate("MainWindow", "Delete selected items", None, QtGui.QApplication.UnicodeUTF8))
        self.action_delete.setShortcut(QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourRed.setText(QtGui.QApplication.translate("MainWindow", "&Red", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourRed.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the colour of selected items to red", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourBlue.setText(QtGui.QApplication.translate("MainWindow", "&Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourBlue.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the colour of selected items to blue", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourGreen.setText(QtGui.QApplication.translate("MainWindow", "&Green", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourGreen.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the colour of selected items to green", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourBlack.setText(QtGui.QApplication.translate("MainWindow", "Blac&k", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourBlack.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the colour of selected items to black", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleSolid.setText(QtGui.QApplication.translate("MainWindow", "&Solid", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleSolid.setToolTip(QtGui.QApplication.translate("MainWindow", "Set pen style for selected items to solid", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleDash.setText(QtGui.QApplication.translate("MainWindow", "&Dash", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleDash.setToolTip(QtGui.QApplication.translate("MainWindow", "Set pen style for selected items to dash", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleDot.setText(QtGui.QApplication.translate("MainWindow", "Do&t", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleDot.setToolTip(QtGui.QApplication.translate("MainWindow", "Set pen style for selected items to dot", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleDashDot.setText(QtGui.QApplication.translate("MainWindow", "D&ash-Dot", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleDashDot.setToolTip(QtGui.QApplication.translate("MainWindow", "Set pen style for selected items to dash-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleDashDotDot.setText(QtGui.QApplication.translate("MainWindow", "Dash-dot-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenStyleDashDotDot.setToolTip(QtGui.QApplication.translate("MainWindow", "Set pen style for selected items to dash-dot-dot", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addCapacitor.setText(QtGui.QApplication.translate("MainWindow", "&Capacitor", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addCapacitor.setToolTip(QtGui.QApplication.translate("MainWindow", "Draws a capacitor", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addGround.setText(QtGui.QApplication.translate("MainWindow", "&Ground", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addGround.setToolTip(QtGui.QApplication.translate("MainWindow", "Draws a ground symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourBlack.setText(QtGui.QApplication.translate("MainWindow", "Blac&k", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourBlack.setToolTip(QtGui.QApplication.translate("MainWindow", "Sets the fill colour to black", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourRed.setText(QtGui.QApplication.translate("MainWindow", "&Red", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourRed.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the fill colour to red", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourBlue.setText(QtGui.QApplication.translate("MainWindow", "&Blue", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourBlue.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the fill colour to blue", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourGreen.setText(QtGui.QApplication.translate("MainWindow", "&Green", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourGreen.setToolTip(QtGui.QApplication.translate("MainWindow", "Set the brush colour to green", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushStyleNone.setText(QtGui.QApplication.translate("MainWindow", "&No fill", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushStyleNone.setToolTip(QtGui.QApplication.translate("MainWindow", "Remove any fill", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushStyleSolid.setText(QtGui.QApplication.translate("MainWindow", "&Solid", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushStyleSolid.setToolTip(QtGui.QApplication.translate("MainWindow", "Fill with a solid colour", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addNPNBJT.setText(QtGui.QApplication.translate("MainWindow", "NPN BJT", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addNPNBJT.setToolTip(QtGui.QApplication.translate("MainWindow", "Add NPN BJT", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addPNPBJT.setText(QtGui.QApplication.translate("MainWindow", "PNP BJT", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addPNPBJT.setToolTip(QtGui.QApplication.translate("MainWindow", "Add PNP BJT", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addNMOSWithArrow.setText(QtGui.QApplication.translate("MainWindow", "With &arrow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addNMOSWithArrow.setToolTip(QtGui.QApplication.translate("MainWindow", "Add N-type MOSFET with arrow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addNMOSWithoutArrow.setText(QtGui.QApplication.translate("MainWindow", "Without arrow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addNMOSWithoutArrow.setToolTip(QtGui.QApplication.translate("MainWindow", "Add N-type MOSFET without arrow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addPMOSWithArrow.setText(QtGui.QApplication.translate("MainWindow", "With &arrow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addPMOSWithArrow.setToolTip(QtGui.QApplication.translate("MainWindow", "Add P-type MOSFET with arrow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addPMOSWithoutArrow.setText(QtGui.QApplication.translate("MainWindow", "Without arrow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addPMOSWithoutArrow.setToolTip(QtGui.QApplication.translate("MainWindow", "Add P-type MOSFET without arrow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveSymbol.setText(QtGui.QApplication.translate("MainWindow", "Save symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveSymbol.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_loadSymbol.setText(QtGui.QApplication.translate("MainWindow", "Load symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.action_loadSymbol.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+L", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveSchematic.setText(QtGui.QApplication.translate("MainWindow", "Save schematic", None, QtGui.QApplication.UnicodeUTF8))
        self.action_saveSchematic.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_loadSchematic.setText(QtGui.QApplication.translate("MainWindow", "Load schematic", None, QtGui.QApplication.UnicodeUTF8))
        self.action_loadSchematic.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addLine.setText(QtGui.QApplication.translate("MainWindow", "&Line", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addRectangle.setText(QtGui.QApplication.translate("MainWindow", "&Rectangle", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addCircle.setText(QtGui.QApplication.translate("MainWindow", "&Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addEllipse.setText(QtGui.QApplication.translate("MainWindow", "&Ellipse", None, QtGui.QApplication.UnicodeUTF8))
        self.action_snapToGrid.setText(QtGui.QApplication.translate("MainWindow", "Sn&ap to grid", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addTextBox.setText(QtGui.QApplication.translate("MainWindow", "&Text box", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourCyan.setText(QtGui.QApplication.translate("MainWindow", "&Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourMagenta.setText(QtGui.QApplication.translate("MainWindow", "&Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setPenColourYellow.setText(QtGui.QApplication.translate("MainWindow", "&Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourCyan.setText(QtGui.QApplication.translate("MainWindow", "&Cyan", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourMagenta.setText(QtGui.QApplication.translate("MainWindow", "&Magenta", None, QtGui.QApplication.UnicodeUTF8))
        self.action_setBrushColourYellow.setText(QtGui.QApplication.translate("MainWindow", "&Yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addDCVoltageSource.setText(QtGui.QApplication.translate("MainWindow", "&Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addDCVoltageSource.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds a DC voltage source", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addDCCurrentSource.setText(QtGui.QApplication.translate("MainWindow", "&Current", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addDCCurrentSource.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds a DC current source", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addACVoltageSource.setText(QtGui.QApplication.translate("MainWindow", "&Voltage", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addACVoltageSource.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds an AC voltage source", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addACCurrentSource.setText(QtGui.QApplication.translate("MainWindow", "&Current", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addACCurrentSource.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds an AC current source", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addVCVS.setText(QtGui.QApplication.translate("MainWindow", "VCVS", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addVCVS.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds a VCVS", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addVCCS.setText(QtGui.QApplication.translate("MainWindow", "VCCS", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addVCCS.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds a VCCS", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addCCVS.setText(QtGui.QApplication.translate("MainWindow", "CCVS", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addCCVS.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds a CCVS", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addCCCS.setText(QtGui.QApplication.translate("MainWindow", "CCCS", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addCCCS.setToolTip(QtGui.QApplication.translate("MainWindow", "Adds a CCCS", None, QtGui.QApplication.UnicodeUTF8))
        self.action_addArc.setText(QtGui.QApplication.translate("MainWindow", "&Arc", None, QtGui.QApplication.UnicodeUTF8))

from drawingarea import DrawingArea
