# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\schematic_mainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1089, 790)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Resources/icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.drawingArea = DrawingArea(self.centralwidget)
        self.drawingArea.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.TextAntialiasing)
        self.drawingArea.setDragMode(QtGui.QGraphicsView.RubberBandDrag)
        self.drawingArea.setCacheMode(QtGui.QGraphicsView.CacheBackground)
        self.drawingArea.setTransformationAnchor(QtGui.QGraphicsView.NoAnchor)
        self.drawingArea.setResizeAnchor(QtGui.QGraphicsView.AnchorUnderMouse)
        self.drawingArea.setViewportUpdateMode(QtGui.QGraphicsView.FullViewportUpdate)
        self.drawingArea.setRubberBandSelectionMode(QtCore.Qt.ContainsItemShape)
        self.drawingArea.setObjectName(_fromUtf8("drawingArea"))
        self.horizontalLayout.addWidget(self.drawingArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1089, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Edit = QtGui.QMenu(self.menubar)
        self.menu_Edit.setObjectName(_fromUtf8("menu_Edit"))
        self.menu_setPenWidth = QtGui.QMenu(self.menu_Edit)
        self.menu_setPenWidth.setObjectName(_fromUtf8("menu_setPenWidth"))
        self.menu_setPenColour = QtGui.QMenu(self.menu_Edit)
        self.menu_setPenColour.setObjectName(_fromUtf8("menu_setPenColour"))
        self.menu_setPenStyle = QtGui.QMenu(self.menu_Edit)
        self.menu_setPenStyle.setObjectName(_fromUtf8("menu_setPenStyle"))
        self.menu_setFillColour = QtGui.QMenu(self.menu_Edit)
        self.menu_setFillColour.setObjectName(_fromUtf8("menu_setFillColour"))
        self.menu_setFillStyle = QtGui.QMenu(self.menu_Edit)
        self.menu_setFillStyle.setObjectName(_fromUtf8("menu_setFillStyle"))
        self.menu_Add = QtGui.QMenu(self.menubar)
        self.menu_Add.setObjectName(_fromUtf8("menu_Add"))
        self.menu_Transistor = QtGui.QMenu(self.menu_Add)
        self.menu_Transistor.setObjectName(_fromUtf8("menu_Transistor"))
        self.menu_N_type_MOSFET = QtGui.QMenu(self.menu_Transistor)
        self.menu_N_type_MOSFET.setObjectName(_fromUtf8("menu_N_type_MOSFET"))
        self.menu_P_type_MOSFET = QtGui.QMenu(self.menu_Transistor)
        self.menu_P_type_MOSFET.setObjectName(_fromUtf8("menu_P_type_MOSFET"))
        self.menu_View = QtGui.QMenu(self.menubar)
        self.menu_View.setObjectName(_fromUtf8("menu_View"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_exportFile = QtGui.QAction(MainWindow)
        self.action_exportFile.setObjectName(_fromUtf8("action_exportFile"))
        self.action_quit = QtGui.QAction(MainWindow)
        self.action_quit.setObjectName(_fromUtf8("action_quit"))
        self.action_move = QtGui.QAction(MainWindow)
        self.action_move.setObjectName(_fromUtf8("action_move"))
        self.action_copy = QtGui.QAction(MainWindow)
        self.action_copy.setObjectName(_fromUtf8("action_copy"))
        self.action_addWire = QtGui.QAction(MainWindow)
        self.action_addWire.setObjectName(_fromUtf8("action_addWire"))
        self.action_addResistor = QtGui.QAction(MainWindow)
        self.action_addResistor.setObjectName(_fromUtf8("action_addResistor"))
        self.action_addDot = QtGui.QAction(MainWindow)
        self.action_addDot.setObjectName(_fromUtf8("action_addDot"))
        self.action_setWidth2 = QtGui.QAction(MainWindow)
        self.action_setWidth2.setCheckable(True)
        self.action_setWidth2.setObjectName(_fromUtf8("action_setWidth2"))
        self.action_setWidth4 = QtGui.QAction(MainWindow)
        self.action_setWidth4.setCheckable(True)
        self.action_setWidth4.setObjectName(_fromUtf8("action_setWidth4"))
        self.action_setWidth6 = QtGui.QAction(MainWindow)
        self.action_setWidth6.setCheckable(True)
        self.action_setWidth6.setObjectName(_fromUtf8("action_setWidth6"))
        self.action_setWidth8 = QtGui.QAction(MainWindow)
        self.action_setWidth8.setCheckable(True)
        self.action_setWidth8.setObjectName(_fromUtf8("action_setWidth8"))
        self.action_setWidth10 = QtGui.QAction(MainWindow)
        self.action_setWidth10.setCheckable(True)
        self.action_setWidth10.setObjectName(_fromUtf8("action_setWidth10"))
        self.action_rotate = QtGui.QAction(MainWindow)
        self.action_rotate.setObjectName(_fromUtf8("action_rotate"))
        self.action_mirror = QtGui.QAction(MainWindow)
        self.action_mirror.setObjectName(_fromUtf8("action_mirror"))
        self.action_fitToView = QtGui.QAction(MainWindow)
        self.action_fitToView.setObjectName(_fromUtf8("action_fitToView"))
        self.action_showGrid = QtGui.QAction(MainWindow)
        self.action_showGrid.setCheckable(True)
        self.action_showGrid.setObjectName(_fromUtf8("action_showGrid"))
        self.action_delete = QtGui.QAction(MainWindow)
        self.action_delete.setObjectName(_fromUtf8("action_delete"))
        self.action_setPenColourRed = QtGui.QAction(MainWindow)
        self.action_setPenColourRed.setCheckable(True)
        self.action_setPenColourRed.setObjectName(_fromUtf8("action_setPenColourRed"))
        self.action_setPenColourBlue = QtGui.QAction(MainWindow)
        self.action_setPenColourBlue.setCheckable(True)
        self.action_setPenColourBlue.setObjectName(_fromUtf8("action_setPenColourBlue"))
        self.action_setPenColourGreen = QtGui.QAction(MainWindow)
        self.action_setPenColourGreen.setCheckable(True)
        self.action_setPenColourGreen.setObjectName(_fromUtf8("action_setPenColourGreen"))
        self.action_setPenColourBlack = QtGui.QAction(MainWindow)
        self.action_setPenColourBlack.setCheckable(True)
        self.action_setPenColourBlack.setObjectName(_fromUtf8("action_setPenColourBlack"))
        self.action_setPenStyleSolid = QtGui.QAction(MainWindow)
        self.action_setPenStyleSolid.setCheckable(True)
        self.action_setPenStyleSolid.setObjectName(_fromUtf8("action_setPenStyleSolid"))
        self.action_setPenStyleDash = QtGui.QAction(MainWindow)
        self.action_setPenStyleDash.setCheckable(True)
        self.action_setPenStyleDash.setObjectName(_fromUtf8("action_setPenStyleDash"))
        self.action_setPenStyleDot = QtGui.QAction(MainWindow)
        self.action_setPenStyleDot.setCheckable(True)
        self.action_setPenStyleDot.setObjectName(_fromUtf8("action_setPenStyleDot"))
        self.action_setPenStyleDashDot = QtGui.QAction(MainWindow)
        self.action_setPenStyleDashDot.setCheckable(True)
        self.action_setPenStyleDashDot.setObjectName(_fromUtf8("action_setPenStyleDashDot"))
        self.action_setPenStyleDashDotDot = QtGui.QAction(MainWindow)
        self.action_setPenStyleDashDotDot.setCheckable(True)
        self.action_setPenStyleDashDotDot.setObjectName(_fromUtf8("action_setPenStyleDashDotDot"))
        self.action_addCapacitor = QtGui.QAction(MainWindow)
        self.action_addCapacitor.setObjectName(_fromUtf8("action_addCapacitor"))
        self.action_addGround = QtGui.QAction(MainWindow)
        self.action_addGround.setObjectName(_fromUtf8("action_addGround"))
        self.action_setBrushColourBlack = QtGui.QAction(MainWindow)
        self.action_setBrushColourBlack.setCheckable(True)
        self.action_setBrushColourBlack.setObjectName(_fromUtf8("action_setBrushColourBlack"))
        self.action_setBrushColourRed = QtGui.QAction(MainWindow)
        self.action_setBrushColourRed.setCheckable(True)
        self.action_setBrushColourRed.setObjectName(_fromUtf8("action_setBrushColourRed"))
        self.action_setBrushColourBlue = QtGui.QAction(MainWindow)
        self.action_setBrushColourBlue.setCheckable(True)
        self.action_setBrushColourBlue.setObjectName(_fromUtf8("action_setBrushColourBlue"))
        self.action_setBrushColourGreen = QtGui.QAction(MainWindow)
        self.action_setBrushColourGreen.setObjectName(_fromUtf8("action_setBrushColourGreen"))
        self.action_setBrushStyleNone = QtGui.QAction(MainWindow)
        self.action_setBrushStyleNone.setCheckable(True)
        self.action_setBrushStyleNone.setObjectName(_fromUtf8("action_setBrushStyleNone"))
        self.action_setBrushStyleSolid = QtGui.QAction(MainWindow)
        self.action_setBrushStyleSolid.setCheckable(True)
        self.action_setBrushStyleSolid.setObjectName(_fromUtf8("action_setBrushStyleSolid"))
        self.actionNPN_BJT = QtGui.QAction(MainWindow)
        self.actionNPN_BJT.setObjectName(_fromUtf8("actionNPN_BJT"))
        self.actionPNP_BJT = QtGui.QAction(MainWindow)
        self.actionPNP_BJT.setObjectName(_fromUtf8("actionPNP_BJT"))
        self.action_addNMOSWithArrow = QtGui.QAction(MainWindow)
        self.action_addNMOSWithArrow.setObjectName(_fromUtf8("action_addNMOSWithArrow"))
        self.action_addNMOSWithoutArrow = QtGui.QAction(MainWindow)
        self.action_addNMOSWithoutArrow.setObjectName(_fromUtf8("action_addNMOSWithoutArrow"))
        self.action_addPMOSWithArrow = QtGui.QAction(MainWindow)
        self.action_addPMOSWithArrow.setObjectName(_fromUtf8("action_addPMOSWithArrow"))
        self.action_addPMOSWithoutArrow = QtGui.QAction(MainWindow)
        self.action_addPMOSWithoutArrow.setObjectName(_fromUtf8("action_addPMOSWithoutArrow"))
        self.action_saveSymbol = QtGui.QAction(MainWindow)
        self.action_saveSymbol.setObjectName(_fromUtf8("action_saveSymbol"))
        self.action_loadSymbol = QtGui.QAction(MainWindow)
        self.action_loadSymbol.setObjectName(_fromUtf8("action_loadSymbol"))
        self.action_saveSchematic = QtGui.QAction(MainWindow)
        self.action_saveSchematic.setObjectName(_fromUtf8("action_saveSchematic"))
        self.action_loadSchematic = QtGui.QAction(MainWindow)
        self.action_loadSchematic.setObjectName(_fromUtf8("action_loadSchematic"))
        self.menu_File.addAction(self.action_saveSchematic)
        self.menu_File.addAction(self.action_loadSchematic)
        self.menu_File.addAction(self.action_saveSymbol)
        self.menu_File.addAction(self.action_loadSymbol)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_exportFile)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_quit)
        self.menu_setPenWidth.addAction(self.action_setWidth2)
        self.menu_setPenWidth.addAction(self.action_setWidth4)
        self.menu_setPenWidth.addAction(self.action_setWidth6)
        self.menu_setPenWidth.addAction(self.action_setWidth8)
        self.menu_setPenWidth.addAction(self.action_setWidth10)
        self.menu_setPenColour.addAction(self.action_setPenColourBlack)
        self.menu_setPenColour.addAction(self.action_setPenColourRed)
        self.menu_setPenColour.addAction(self.action_setPenColourBlue)
        self.menu_setPenColour.addAction(self.action_setPenColourGreen)
        self.menu_setPenStyle.addAction(self.action_setPenStyleSolid)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDash)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDot)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDashDot)
        self.menu_setPenStyle.addAction(self.action_setPenStyleDashDotDot)
        self.menu_setFillColour.addAction(self.action_setBrushColourBlack)
        self.menu_setFillColour.addAction(self.action_setBrushColourRed)
        self.menu_setFillColour.addAction(self.action_setBrushColourBlue)
        self.menu_setFillColour.addAction(self.action_setBrushColourGreen)
        self.menu_setFillStyle.addAction(self.action_setBrushStyleNone)
        self.menu_setFillStyle.addAction(self.action_setBrushStyleSolid)
        self.menu_Edit.addAction(self.action_delete)
        self.menu_Edit.addAction(self.action_move)
        self.menu_Edit.addAction(self.action_copy)
        self.menu_Edit.addAction(self.action_rotate)
        self.menu_Edit.addAction(self.action_mirror)
        self.menu_Edit.addAction(self.menu_setPenWidth.menuAction())
        self.menu_Edit.addAction(self.menu_setPenColour.menuAction())
        self.menu_Edit.addAction(self.menu_setPenStyle.menuAction())
        self.menu_Edit.addAction(self.menu_setFillColour.menuAction())
        self.menu_Edit.addAction(self.menu_setFillStyle.menuAction())
        self.menu_N_type_MOSFET.addAction(self.action_addNMOSWithArrow)
        self.menu_N_type_MOSFET.addAction(self.action_addNMOSWithoutArrow)
        self.menu_P_type_MOSFET.addAction(self.action_addPMOSWithArrow)
        self.menu_P_type_MOSFET.addAction(self.action_addPMOSWithoutArrow)
        self.menu_Transistor.addAction(self.menu_N_type_MOSFET.menuAction())
        self.menu_Transistor.addAction(self.menu_P_type_MOSFET.menuAction())
        self.menu_Transistor.addAction(self.actionNPN_BJT)
        self.menu_Transistor.addAction(self.actionPNP_BJT)
        self.menu_Add.addAction(self.action_addWire)
        self.menu_Add.addAction(self.action_addResistor)
        self.menu_Add.addAction(self.action_addCapacitor)
        self.menu_Add.addAction(self.action_addGround)
        self.menu_Add.addAction(self.action_addDot)
        self.menu_Add.addAction(self.menu_Transistor.menuAction())
        self.menu_View.addAction(self.action_fitToView)
        self.menu_View.addAction(self.action_showGrid)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Edit.menuAction())
        self.menubar.addAction(self.menu_View.menuAction())
        self.menubar.addAction(self.menu_Add.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Schematic draw", None))
        self.menu_File.setTitle(_translate("MainWindow", "&File", None))
        self.menu_Edit.setTitle(_translate("MainWindow", "&Edit", None))
        self.menu_setPenWidth.setTitle(_translate("MainWindow", "&Width", None))
        self.menu_setPenColour.setTitle(_translate("MainWindow", "&Colour", None))
        self.menu_setPenStyle.setTitle(_translate("MainWindow", "&Pen style", None))
        self.menu_setFillColour.setTitle(_translate("MainWindow", "Fill colour", None))
        self.menu_setFillStyle.setTitle(_translate("MainWindow", "Fill style", None))
        self.menu_Add.setTitle(_translate("MainWindow", "&Add", None))
        self.menu_Transistor.setTitle(_translate("MainWindow", "&Transistor", None))
        self.menu_N_type_MOSFET.setTitle(_translate("MainWindow", "&N-type MOSFET", None))
        self.menu_P_type_MOSFET.setTitle(_translate("MainWindow", "&P-type MOSFET", None))
        self.menu_View.setTitle(_translate("MainWindow", "&View", None))
        self.action_exportFile.setText(_translate("MainWindow", "Export file", None))
        self.action_exportFile.setToolTip(_translate("MainWindow", "Exports file as an image", None))
        self.action_exportFile.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.action_quit.setText(_translate("MainWindow", "Quit", None))
        self.action_quit.setToolTip(_translate("MainWindow", "Quits the program", None))
        self.action_quit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.action_move.setText(_translate("MainWindow", "Move", None))
        self.action_move.setToolTip(_translate("MainWindow", "Move selected items", None))
        self.action_move.setShortcut(_translate("MainWindow", "M", None))
        self.action_copy.setText(_translate("MainWindow", "Copy", None))
        self.action_copy.setToolTip(_translate("MainWindow", "Copy selected items", None))
        self.action_copy.setShortcut(_translate("MainWindow", "C", None))
        self.action_addWire.setText(_translate("MainWindow", "&Wire", None))
        self.action_addWire.setToolTip(_translate("MainWindow", "Draws a wire", None))
        self.action_addResistor.setText(_translate("MainWindow", "&Resistor", None))
        self.action_addResistor.setToolTip(_translate("MainWindow", "Draws a resistor", None))
        self.action_addDot.setText(_translate("MainWindow", "Connection &dot", None))
        self.action_addDot.setToolTip(_translate("MainWindow", "Draws a dot signifying connectivity", None))
        self.action_setWidth2.setText(_translate("MainWindow", "2", None))
        self.action_setWidth2.setToolTip(_translate("MainWindow", "Sets the width of currently selected items to 2", None))
        self.action_setWidth4.setText(_translate("MainWindow", "4", None))
        self.action_setWidth4.setToolTip(_translate("MainWindow", "Sets the width of currently selected items to 4", None))
        self.action_setWidth6.setText(_translate("MainWindow", "6", None))
        self.action_setWidth6.setToolTip(_translate("MainWindow", "Sets the width of currently selected items to 6", None))
        self.action_setWidth8.setText(_translate("MainWindow", "8", None))
        self.action_setWidth8.setToolTip(_translate("MainWindow", "Sets the width of currently selected items to 8", None))
        self.action_setWidth10.setText(_translate("MainWindow", "10", None))
        self.action_setWidth10.setToolTip(_translate("MainWindow", "Sets the width of currently selected items to 10", None))
        self.action_rotate.setText(_translate("MainWindow", "Rotate", None))
        self.action_rotate.setToolTip(_translate("MainWindow", "Rotate selected items", None))
        self.action_rotate.setShortcut(_translate("MainWindow", "R", None))
        self.action_mirror.setText(_translate("MainWindow", "Mirror", None))
        self.action_mirror.setToolTip(_translate("MainWindow", "Mirror selected items", None))
        self.action_mirror.setShortcut(_translate("MainWindow", "Shift+R", None))
        self.action_fitToView.setText(_translate("MainWindow", "Fit to view", None))
        self.action_fitToView.setShortcut(_translate("MainWindow", "F", None))
        self.action_showGrid.setText(_translate("MainWindow", "Show grid", None))
        self.action_showGrid.setToolTip(_translate("MainWindow", "Toggle grid visibility", None))
        self.action_showGrid.setShortcut(_translate("MainWindow", "G", None))
        self.action_delete.setText(_translate("MainWindow", "Delete", None))
        self.action_delete.setToolTip(_translate("MainWindow", "Delete selected items", None))
        self.action_delete.setShortcut(_translate("MainWindow", "D", None))
        self.action_setPenColourRed.setText(_translate("MainWindow", "&Red", None))
        self.action_setPenColourRed.setToolTip(_translate("MainWindow", "Set the colour of selected items to red", None))
        self.action_setPenColourBlue.setText(_translate("MainWindow", "&Blue", None))
        self.action_setPenColourBlue.setToolTip(_translate("MainWindow", "Set the colour of selected items to blue", None))
        self.action_setPenColourGreen.setText(_translate("MainWindow", "&Green", None))
        self.action_setPenColourGreen.setToolTip(_translate("MainWindow", "Set the colour of selected items to green", None))
        self.action_setPenColourBlack.setText(_translate("MainWindow", "Blac&k", None))
        self.action_setPenColourBlack.setToolTip(_translate("MainWindow", "Set the colour of selected items to black", None))
        self.action_setPenStyleSolid.setText(_translate("MainWindow", "&Solid", None))
        self.action_setPenStyleSolid.setToolTip(_translate("MainWindow", "Set pen style for selected items to solid", None))
        self.action_setPenStyleDash.setText(_translate("MainWindow", "&Dash", None))
        self.action_setPenStyleDash.setToolTip(_translate("MainWindow", "Set pen style for selected items to dash", None))
        self.action_setPenStyleDot.setText(_translate("MainWindow", "Do&t", None))
        self.action_setPenStyleDot.setToolTip(_translate("MainWindow", "Set pen style for selected items to dot", None))
        self.action_setPenStyleDashDot.setText(_translate("MainWindow", "D&ash-Dot", None))
        self.action_setPenStyleDashDot.setToolTip(_translate("MainWindow", "Set pen style for selected items to dash-dot", None))
        self.action_setPenStyleDashDotDot.setText(_translate("MainWindow", "Dash-dot-dot", None))
        self.action_setPenStyleDashDotDot.setToolTip(_translate("MainWindow", "Set pen style for selected items to dash-dot-dot", None))
        self.action_addCapacitor.setText(_translate("MainWindow", "&Capacitor", None))
        self.action_addCapacitor.setToolTip(_translate("MainWindow", "Draws a capacitor", None))
        self.action_addGround.setText(_translate("MainWindow", "&Ground", None))
        self.action_addGround.setToolTip(_translate("MainWindow", "Draws a ground symbol", None))
        self.action_setBrushColourBlack.setText(_translate("MainWindow", "Blac&k", None))
        self.action_setBrushColourBlack.setToolTip(_translate("MainWindow", "Sets the fill colour to black", None))
        self.action_setBrushColourRed.setText(_translate("MainWindow", "&Red", None))
        self.action_setBrushColourRed.setToolTip(_translate("MainWindow", "Set the fill colour to red", None))
        self.action_setBrushColourBlue.setText(_translate("MainWindow", "&Blue", None))
        self.action_setBrushColourBlue.setToolTip(_translate("MainWindow", "Set the fill colour to blue", None))
        self.action_setBrushColourGreen.setText(_translate("MainWindow", "&Green", None))
        self.action_setBrushColourGreen.setToolTip(_translate("MainWindow", "Set the brush colour to green", None))
        self.action_setBrushStyleNone.setText(_translate("MainWindow", "&No fill", None))
        self.action_setBrushStyleNone.setToolTip(_translate("MainWindow", "Remove any fill", None))
        self.action_setBrushStyleSolid.setText(_translate("MainWindow", "&Solid", None))
        self.action_setBrushStyleSolid.setToolTip(_translate("MainWindow", "Fill with a solid colour", None))
        self.actionNPN_BJT.setText(_translate("MainWindow", "NPN BJT", None))
        self.actionPNP_BJT.setText(_translate("MainWindow", "PNP BJT", None))
        self.action_addNMOSWithArrow.setText(_translate("MainWindow", "With &arrow", None))
        self.action_addNMOSWithArrow.setToolTip(_translate("MainWindow", "Add N-type MOSFET with arrow", None))
        self.action_addNMOSWithoutArrow.setText(_translate("MainWindow", "Without arrow", None))
        self.action_addNMOSWithoutArrow.setToolTip(_translate("MainWindow", "Add N-type MOSFET without arrow", None))
        self.action_addPMOSWithArrow.setText(_translate("MainWindow", "With &arrow", None))
        self.action_addPMOSWithArrow.setToolTip(_translate("MainWindow", "Add P-type MOSFET with arrow", None))
        self.action_addPMOSWithoutArrow.setText(_translate("MainWindow", "Without arrow", None))
        self.action_addPMOSWithoutArrow.setToolTip(_translate("MainWindow", "Add P-type MOSFET without arrow", None))
        self.action_saveSymbol.setText(_translate("MainWindow", "Save symbol", None))
        self.action_saveSymbol.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.action_loadSymbol.setText(_translate("MainWindow", "Load symbol", None))
        self.action_loadSymbol.setShortcut(_translate("MainWindow", "Ctrl+Shift+L", None))
        self.action_saveSchematic.setText(_translate("MainWindow", "Save schematic", None))
        self.action_saveSchematic.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_loadSchematic.setText(_translate("MainWindow", "Load schematic", None))
        self.action_loadSchematic.setShortcut(_translate("MainWindow", "Ctrl+L", None))

from drawingarea import DrawingArea
